### ISSUE TITLE
参考文献正文是小四号

### ISSUE THREAD

**Issue by Komari-Koshigaya** [mengchaoheng/SCUT_thesis#10]
`\newcommand{\refbodyfont}{\songti\wuhao\normalfont}          % 参考文献字体` （scutthesis.cls）
这部分代码是在控制参考文献正文字号为五号吧？

但为啥编译出来的pdf是小四号？

另外，我在cls文件中看到下述代码
```cls
\AtBeginDocument{\CJKindent{}%
    \makeindex%
    \normalsize%正文字体格式
    \linespacing{1.682}% 主行距～1.5倍
  }
\AtEndDocument{}
```
正文行间距不是1.5倍吗？ 这里不写1.5而写成1.682是有什么说法吗

**Comment by mengchaoheng** [comment]
第一个问题，我还是不是很清楚您指的是哪个地方字号不对。
第二个问题，行距这个我百度过，说行距的概念和word的不一样。这部分从前面的模版继承过来没改过。我想可以从其他提供官方模版的学校那里看看是否是这样设置行距。

**Comment by mengchaoheng** [comment]
> `\newcommand{\refbodyfont}{\songti\wuhao\normalfont}          % 参考文献字体` （scutthesis.cls）
> 
> 这部分代码是在控制参考文献正文字号为五号吧？
> 
> 
> 
> 但为啥编译出来的pdf是小四号？
> 
> 
> 
> 
> 
> 另外，我在cls文件中看到下述代码
> 
> ```cls
> 
> \AtBeginDocument{\CJKindent{}%
> 
>     \makeindex%
> 
>     \normalsize%正文字体格式
> 
>     \linespacing{1.682}% 主行距～1.5倍
> 
>   }
> 
> \AtEndDocument{}
> 
> ```
> 
> 正文行间距不是1.5倍吗？ 这里不写1.5而写成1.682是有什么说法吗

是哪部分是小四号？

**Comment by Komari-Koshigaya** [comment]
这个是参考文献里的
![image](https://user-images.githubusercontent.com/39209375/162610977-22d1feeb-1f29-4237-8f0b-24104a8ef52e.png)

可以看到和正文里的字号一样 都是小四
![image](https://user-images.githubusercontent.com/39209375/162611017-33d77d5d-4bc8-4fb8-af7d-99636b58ce01.png)

**Comment by mengchaoheng** [comment]
> 这个是参考文献里的 ![image](https://user-images.githubusercontent.com/39209375/162610977-22d1feeb-1f29-4237-8f0b-24104a8ef52e.png)
> 
> 可以看到和正文里的字号一样 都是小四 ![image](https://user-images.githubusercontent.com/39209375/162611017-33d77d5d-4bc8-4fb8-af7d-99636b58ce01.png)

昨天回复失败

**Comment by mengchaoheng** [comment]
> 这个是参考文献里的 ![image](https://user-images.githubusercontent.com/39209375/162610977-22d1feeb-1f29-4237-8f0b-24104a8ef52e.png)
> 
> 可以看到和正文里的字号一样 都是小四 ![image](https://user-images.githubusercontent.com/39209375/162611017-33d77d5d-4bc8-4fb8-af7d-99636b58ce01.png)

才发现昨天回复失败。明白了。这是参考文献著录，这部分并没有使用
```

\newcommand{\refbodyfont}{\songti\wuhao\normalfont} % 参考文献字体
```
进行控制，因为我们使用了新的包，biblatex。

其次就是参考文献的字号是多少，论文撰写规范并没有规定，我就设置为和正文一样，但如果要改的话应该是改scutthesis.tex的biblatex包设置。

**Comment by mengchaoheng** [comment]
或许您有不同看法？我问了实验室在写论文的硕博士，他们表示现在的字号就可以接受。

**Comment by mengchaoheng** [comment]
```
%参考文献设置
\usepackage[backend=biber,style=gb7714-2015,gbalign=gb7714-2015,gbpub=false,gbnamefmt = lowercase]{biblatex}
```
这里控制了参考文献格式，我还没查过，应该是这个包的属性可以控制字号。

**Comment by Komari-Koshigaya** [comment]
查了一下 不是在`\usepackage[backend=biber,style=gb7714-2015,gbalign=gb7714-2015,gbpub=false,gbnamefmt = lowercase]{biblatex}`设置

而是通过`\renewcommand*{\bibfont}{\small}`控制  （参考 [https://tex.stackexchange.com/questions/205432](https://tex.stackexchange.com/questions/205432)）

供有同样需求的人参考

**Comment by Komari-Koshigaya** [comment]
还有几天 周五提交送审
行 我提个pr吧 但我只是在Windows下测的 不知道其它系统能不能用

**Comment by mengchaoheng** [comment]
> 还有几天 周五提交送审 行 我提个pr吧 但我只是在Windows下测的 不知道其它系统能不能用

等一下，我刚刚合并另一个pr，现在可以重新建立提及了。我不知道会不会冲突，原谅我不会处理复杂提及冲突的问题。

**Comment by mengchaoheng** [comment]
不用担心系统问题，控制字号是和系统无关的操作。辛苦了！

**Comment by mengchaoheng** [comment]
先别提交论文，.cls文件的五号字体定义错了，10.95改10.5。我的锅，没仔细审查祖传代码！

**Comment by Komari-Koshigaya** [comment]
> 先别提交论文，.cls文件的五号字体定义错了，10.95改10.5。我的锅，没仔细审查祖传代码！
好的 我改一下

你怎么发现的  上一届不是反应通过了学校审查吗，怎么字号不对，后面改了吗

**Comment by mengchaoheng** [comment]
差别很小看不出来，大概一个字的1/20左右？以往的都过审了。这是另一个模版继承来的错误，坑啊。我实验室的说影响不大不改了，有的已经提交了。强迫症的话不改不行

**Comment by mengchaoheng** [comment]
> > 先别提交论文，.cls文件的五号字体定义错了，10.95改10.5。我的锅，没仔细审查祖传代码！
> 
> 好的 我改一下
> 
> 
> 
> 你怎么发现的  上一届不是反应通过了学校审查吗，怎么字号不对，后面改了吗
> 
> 
> 
> 
> 
> 
我在更新pub文件的时候想把里面的字体改为五号，发现效果和官方给的word不一样（一行差两个字）。然后仔细看才发现的。这个会影响图标题，页眉，还有参考文献字体（如果使用了small）

**Comment by mengchaoheng** [comment]
https://github.com/yecfly/scut-thesis/issues/1
从这里来的错误

**Comment by mengchaoheng** [comment]
> `\newcommand{\refbodyfont}{\songti\wuhao\normalfont}          % 参考文献字体` （scutthesis.cls）
> 
> 这部分代码是在控制参考文献正文字号为五号吧？
> 
> 
> 
> 但为啥编译出来的pdf是小四号？
> 
> 
> 
> 
> 
> 另外，我在cls文件中看到下述代码
> 
> ```cls
> 
> \AtBeginDocument{\CJKindent{}%
> 
>     \makeindex%
> 
>     \normalsize%正文字体格式
> 
>     \linespacing{1.682}% 主行距～1.5倍
> 
>   }
> 
> \AtEndDocument{}
> 
> ```
> 
> 正文行间距不是1.5倍吗？ 这里不写1.5而写成1.682是有什么说法吗

所以这个地方1.682我也要仔细审查一下

**Comment by Komari-Koshigaya** [comment]
> 所以这个地方1.682我也要仔细审查一下
 拜托了![1A2L{B}FUPY008~ 20I014A](https://user-images.githubusercontent.com/39209375/163104356-5c1c3eff-dd61-4e50-95b3-7c4dd86ad1da.png)

 我也看看 不过latex字号这块我不是很明白，我看`ishort-zh-cn.pdf` P72中
![image](https://user-images.githubusercontent.com/39209375/163104567-f1718e4b-e958-4885-a454-e8ae78219d3d.png)
11pt 12pt选项是什么意思，上面也是10.95pt ，这样的话 我刚提的pr里面的写法可能也得改下

**Comment by Komari-Koshigaya** [comment]
> 10.95

对的 我刚提的pr中用了 `\small`

`pub.tex` 字号不一样 这个问题 是不是可以和封面一样，提供`.docx`，导出pdf再引入

**Comment by Komari-Koshigaya** [comment]
> 我在更新pub文件的时候想把里面的字体改为五号，发现效果和官方给的word不一样（一行差两个字）。然后仔细看才发现的。这个会影响图标题，页眉，还有参考文献字体（如果使用了small）
 
对的 我刚提的pr中用了 `\small`

`pub.tex` 字号不一样 这个问题 是不是可以和封面一样，提供`.docx`，导出pdf再引入

**Comment by Komari-Koshigaya** [comment]
二号和三号字体定义是不是不对
```tex

\newcommand{\erhao}{\fontsize{21pt}{24pt}\selectfont}  %  改成 22pt?  后面的24pt表示什么意思？
\newcommand{\sanhao}{\fontsize{15.75pt}{18pt}\selectfont}  % 改成 16pt?
```

我在 [【LaTeX入门】03、设置字体相关命令](https://blog.csdn.net/xiazdong/article/details/8892070)看到了一个word字号和pt的转换表
![image](https://user-images.githubusercontent.com/39209375/163106802-1a908fab-37a9-44bc-a84f-1510baed9658.png)

**Comment by mengchaoheng** [comment]
我还在看资料，其他学校的好像也不统一，谷歌也有很多种说法，我再看看。你可以先不管，先搞论文内容。格式的事交给我。

**Comment by mengchaoheng** [comment]
> 二号和三号字体定义是不是不对
> 
> ```tex
> 
> 
> 
> \newcommand{\erhao}{\fontsize{21pt}{24pt}\selectfont}  %  改成 22pt?  后面的24pt表示什么意思？
> 
> \newcommand{\sanhao}{\fontsize{15.75pt}{18pt}\selectfont}  % 改成 16pt?
> 
> ```
> 
> 
> 
> 我在 [【LaTeX入门】03、设置字体相关命令](https://blog.csdn.net/xiazdong/article/details/8892070)看到了一个word字号和pt的转换表
> 
> ![image](https://user-images.githubusercontent.com/39209375/163106802-1a908fab-37a9-44bc-a84f-1510baed9658.png)
> 
> 

原作者回复了，就在前面我发的链接。第一个参数肯定是要改10.5的，原因我大概知道了，稍后整理一下搜到但资料。但第二个参数我还有不是很清楚。

**Comment by mengchaoheng** [comment]
“这是往届师兄设的，可能是因为生成PDF版本时兼容性问题。你也可以设成10.5，问题都不大，直接用10.95也可以，差别应该不大。”--原作者回复10.95的原因。
