### ISSUE TITLE
封面thesis_cover显示不全

### ISSUE THREAD

**Issue by jt-chairman** [mengchaoheng/SCUT_thesis#24]
作者您好！问题是这样的。
在doc编辑好转成pdf是正常的，可以查看到pdf所有页面显示正常，但是在latex导入后第六页空白是怎么回事？

**Comment by mengchaoheng** [comment]
@jt-chairman 有些空白是故意加的。请仔细甄别

**Comment by jt-chairman** [comment]
> @jt-chairman 有些空白是故意加的。请仔细甄别

第六页 是带有学号和学校代号的一页，而且word转出来的pdf也是显示正常，导入后变成空白的。

**Comment by jt-chairman** [comment]
而且我用原有的的doc(报错少一页，加上一页之后)转pdf也有同样的问题。

**Comment by mengchaoheng** [comment]
@jt-chairman 有看我的论文吗？有没有参照我的来？可以试试。从没有人提过这个问题，我也不是很清楚怎么回事。

**Comment by mengchaoheng** [comment]
请仔细检查代码是否注释了草稿封面并且使用了正确的代码

**Comment by jt-chairman** [comment]
我阅读了您的tutorial，也是根据原有的scutthesis.tex作修改，我这边检查一下吧，谢谢！

**Comment by jt-chairman** [comment]
> doc文件可能有问题，但很灵活，自己添加一下必要的空白页即可，得到thesis_cover.pdf文件后添加。最后代码里使用这个文件即可。

好的

**Comment by jt-chairman** [comment]
查到问题是插页的位置有问题，应单数面是有文字，双数面是空白。

**Comment by york-yan** [comment]
-------自动回复 ------
您好，来信已收到，我会尽快处理。祝工作顺利！

**Comment by mengchaoheng** [comment]
插页这个不碍事其实，可以很简单低自定义，也可以不管，最终打印店会帮你留空页

**Comment by jt-chairman** [comment]
> 插页这个不碍事其实，可以很简单低自定义，也可以不管，最终打印店会帮你留空页

非常感谢，是我个人纰漏。
