### ISSUE TITLE
请问一下，目录页中插图目录和表格目录该怎么去除？

### ISSUE THREAD

**Issue by york-yan** [mengchaoheng/SCUT_thesis#25]
请问一下，目录页中插图目录和表格目录该怎么去除？
\tableofcontents %目录
%\listoffigures %插图目录（可选）
%\listoftables %表格目录（可选）
这里注释了还是会有插图和表格目录。如果不注释就会出现两次插图和表格的目录。请问是在cls文件中哪一行代码修改呢？谢谢

**Comment by mengchaoheng** [comment]
cls文件看看注释找到相关的东西测试一下效果，太久不看我一时间想不起来语法。我很好奇为什么不要图表目录，你确定你的论文没有图表吗？

**Comment by mengchaoheng** [comment]
@york-yan

**Comment by york-yan** [comment]
-------自动回复 ------
您好，来信已收到，我会尽快处理。祝工作顺利！

**Comment by mengchaoheng** [comment]
如果他们是独立的一页，你打不了打印的时候去掉他不打印即可，到时候打印店帮你做这个事。电子版的话，PDF阅读器直接删除即可。

**Comment by york-yan** [comment]
哦哦，好的谢谢

**Comment by mengchaoheng** [comment]
> 有图表，但是往年的师兄师姐写的都是没有图表目录的

可以有，不碍事，另外，我记得注释掉代码就行了，还不行的话可能就在cls文件那里曾经修复过什么bug导致注释主文件的目录代码失效。

**Comment by mengchaoheng** [comment]
注释67-76行那部分看看行不行。因为反复根据大家已经修改过，所以难免有版本问题，就是注释掉了的代码冗余导致误导了。还有就是我建议用图表目录，比较美观，而且刚刚毕业这批人都用了这个设计，没问题

**Comment by mengchaoheng** [comment]
@york-yan 不知道能不能收到提示，GitHub很烦，所以我还是圈一下你。尽快完成论文撰写，加油

**Comment by york-yan** [comment]
收到！那我也用这个图标目录吧
