### ISSUE TITLE
references.bib没有起作用

### ISSUE THREAD

**Issue by heslowen** [mengchaoheng/SCUT_thesis#26]
求大佬帮忙看看为啥我的参考文献好像没起作用：
参考文献设置：
![image](https://user-images.githubusercontent.com/22348625/217494282-43e785da-0076-423b-b610-c56c21003156.png)

编译的时候显示：
![image](https://user-images.githubusercontent.com/22348625/217493092-42f99d83-1266-4197-b853-7aec92b77da5.png)

TexStudio的设置：
![image](https://user-images.githubusercontent.com/22348625/217493542-a7c2d658-54f0-4e39-a454-92c33f761f52.png)
![image](https://user-images.githubusercontent.com/22348625/217493873-6e9a7a4c-852d-468a-9db0-151bd19c7a7e.png)

bib文件应该是没有问题的，我是直接复制别人的。

如果使用：\bibliography{reference/references.bib}
![image](https://user-images.githubusercontent.com/22348625/217494622-21956628-87f2-4db2-a373-2e9471ceff55.png)
那编译出来是这样的：
![image](https://user-images.githubusercontent.com/22348625/217495117-92f52557-18be-4fe9-9f2d-9fbaae1e23b3.png)

**Comment by mengchaoheng** [comment]
![image](https://user-images.githubusercontent.com/43166007/217496022-98062d7f-3a07-4881-ad72-c9609e623d02.png)
你看看这个图的提示，找到这个名字是在哪里，就是哪里的问题。正常来说你在论文tex里引用一个文章，这串字符要在bib里找到对应的文章。再不行的话重新排查一下bib文件，记得论文里的引用需要在这个文件里全都有，否则你就引用多个文件，宁多不能少

**Comment by heslowen** [comment]
> ![image](https://user-images.githubusercontent.com/43166007/217496022-98062d7f-3a07-4881-ad72-c9609e623d02.png) 你看看这个图的提示，找到这个名字是在哪里，就是哪里的问题。正常来说你在论文tex里引用一个文章，这串字符要在bib里找到对应的文章。再不行的话重新排查一下bib文件，记得论文里的引用需要在这个文件里全都有，否则你就引用多个文件，宁多不能少

是bib文件里面全部的引用都不work，里面的引用都是我去google scholar复制出来然后直接写进去的，应该是没有问题的，也不会全部都不行。

**Comment by heslowen** [comment]
> > ![image](https://user-images.githubusercontent.com/43166007/217496022-98062d7f-3a07-4881-ad72-c9609e623d02.png) 你看看这个图的提示，找到这个名字是在哪里，就是哪里的问题。正常来说你在论文tex里引用一个文章，这串字符要在bib里找到对应的文章。再不行的话重新排查一下bib文件，记得论文里的引用需要在这个文件里全都有，否则你就引用多个文件，宁多不能少
> 
> 是bib文件里面全部的引用都不work，里面的引用都是我去google scholar复制出来然后直接写进去的，应该是没有问题的，也不会全部都不行。

论文里面的引用格式应该也没问题的
![image](https://user-images.githubusercontent.com/22348625/217497908-054e9a1e-5ce4-44ed-9e0f-a843492b1266.png)


> ![image](https://user-images.githubusercontent.com/43166007/217496022-98062d7f-3a07-4881-ad72-c9609e623d02.png) 你看看这个图的提示，找到这个名字是在哪里，就是哪里的问题。正常来说你在论文tex里引用一个文章，这串字符要在bib里找到对应的文章。再不行的话重新排查一下bib文件，记得论文里的引用需要在这个文件里全都有，否则你就引用多个文件，宁多不能少

论文里的引用格式也没问题的，感觉像是没有读到bib文件。
![image](https://user-images.githubusercontent.com/22348625/217498015-8539637d-c469-460a-9f79-2eefbc090e21.png)

**Comment by mengchaoheng** [comment]
你把bib文件里随便一个文章的元数据发给我，我测试一下

**Comment by mengchaoheng** [comment]
你得确定引用路径对不对，这么严重的问题这么多人都没遇到应该是特例

**Comment by heslowen** [comment]
> 这么多人都没遇到应该

@article{hogan2021knowledge,
	author = {Hogan, Aidan and Blomqvist, Eva and Cochez, Michael and d'Amato, Claudia and Melo, Gerard de and Gutierrez, Claudio and Kirrane, Sabrina and Gayo, Jos{\'e} Emilio Labra and Navigli, Roberto and Neumaier, Sebastian and others},
	journal = {Synthesis Lectures on Data, Semantics, and Knowledge},
	number = {2},
	pages = {1--257},
	publisher = {Morgan \& Claypool Publishers},
	title = {Knowledge graphs},
	volume = {12},
	year = {2021}
}

**Comment by mengchaoheng** [comment]
等等我还在中区食堂，一会回实验室测试

**Comment by mengchaoheng** [comment]
直觉告诉我你的路径有问题，win和Mac的路径的斜杠方向不一样，你试一下

**Comment by mengchaoheng** [comment]
你把路径的斜杠反过来，不好意思我是macOS所以跟你们反过来的。

**Comment by mengchaoheng** [comment]
然后你要用绝对路径试试？最好就是把这个bib文件放论文模版根目录下

**Comment by mengchaoheng** [comment]
解决了吗？建议你换到vscode上用，比较舒适

**Comment by mengchaoheng** [comment]
[vscode配置方法](https://github.com/mengchaoheng/SCUT_thesis/discussions/6) @heslowen

**Comment by heslowen** [comment]
> 直觉告诉我你的路径有问题，win和Mac的路径的斜杠方向不一样，你试一下

确实是路径问题哈，改了之后就可以了。十分感谢大佬!!!
