### ISSUE TITLE
参考文献显示格式好像不对

### ISSUE THREAD

**Issue by zhongchaocheng** [mengchaoheng/SCUT_thesis#27]
首先感谢作者大大的辛勤付出，使用这个模板方便了很多。
我在测试模板导入参考文献的时候，得到的是这样的
![image](https://user-images.githubusercontent.com/8842648/220002354-bf1c5931-d0b0-49b4-8d9c-44f5ef1a77fa.png)
这里有一篇硕士论文，一篇EI会议，一篇期刊文章，但是好像显示的格式和我师兄论文里的不太一样。
![6523ee9607adb1bbb4675cfb57f04a3](https://user-images.githubusercontent.com/8842648/220002468-77c2e72a-2bc7-48ae-803c-27d729593a63.png)
![1bee522c8567c94978ff8c1e5ac75ab](https://user-images.githubusercontent.com/8842648/220002483-bb5d69b2-8565-4011-a5c4-6706f8c12f64.png)
![6f1e81319aaab6f6a1f88fe2262a336](https://user-images.githubusercontent.com/8842648/220002499-950b4917-a58c-4754-91f3-e03fb7cc55c2.png)

这个是需要修改什么格式文件吗

**Comment by mengchaoheng** [comment]
最好看看你的bib文件元数据的正确性。另外建议最好核实一下正确的格式是怎样，有时候你师兄不一定是对的（当然现在他似乎是对的）。

**Comment by mengchaoheng** [comment]
还有就是尽量避免引用中文硕博士论文，你直接找的该作者的小论文（在他论文里最后已发表文献处），引用小论文比较好。中文学位论文的元数据有时候并不是很好，特别是知网这种垃圾。

**Comment by mengchaoheng** [comment]
对于ei会议和期刊，需要保证元数据的内容是国标需要的，国标不需要的可以删除。当然有些是没有特别规定的，按照自己习惯进行即可。

**Comment by zhongchaocheng** [comment]
好的，我查看了bib文件的元数据，去掉了指导老师的信息就好了。其他问题应该可以通过修改bib文件的数据来解决。感谢大佬
