### ISSUE TITLE
目录中含有目录

### ISSUE THREAD

**Issue by Komari-Koshigaya** [mengchaoheng/SCUT_thesis#3]
![image](https://user-images.githubusercontent.com/39209375/155280449-c1572bed-7486-44ee-9896-a82babbb842b.png)
如上图，正常来说，目录中不应该还有目录的超链接吧？这个有办法去掉吗？

最好的效果应该是目录里没有目录的超链接，但生成的pdf书签里有。
我看cls文件里也没有相关代码

**Comment by mengchaoheng** [comment]
已经私信回复

**Comment by Komari-Koshigaya** [comment]
没看到诶   github没私信者功能吧

**Comment by mengchaoheng** [comment]
> 没看到github没有私信者功能吧

我收到您的消息之后，一个小时内在邮件回复您了，没收到吗？别吓我

**Comment by Komari-Koshigaya** [comment]
只收到了github的提示邮件

**Comment by Komari-Koshigaya** [comment]
你能看到我的邮箱地址吗

**Comment by mengchaoheng** [comment]
> 你能看到我的邮箱地址吗

好吧我才知道不能直接在邮箱回复。上一个issue我就是直接在邮箱回复呀。
我贴出来吧：
1.理论上可以，我暂时不知道怎么做。不过这个有什么影响吗？请问是报错了还是和论文撰写规范
冲突？
2.cls文件有些地方我修改了，而是使用一些库函数达到同样的效果。时间有点久远我也忘了具体细节。如果不影响论文撰写也没有报错、没有和撰写规范冲突的话就可以不管它

**Comment by Komari-Koshigaya** [comment]
@mengchaoheng 撰写规范上没有写这么细 主要是我看知网上的论文不会在目录里链接目录的

**Comment by mengchaoheng** [comment]
这部分我暂时没调研过，也暂时没找到办法解决。使用了现在的版本的同学都通过审核了，说明也能用。如果实在在意这点的话，您可以使用其他模板，比如我给出链接的那几个。或者您解决了这个问题的话欢迎分享出您的解决方案。

另：我刚刚更新了一下模板。

**Comment by mengchaoheng** [comment]
> @mengchaoheng 撰写规范上没有写这么细 主要是我看知网上的论文不会在目录里链接目录的

等等，我的论文好像没有出现您说到情况，我查一下什么情况

**Comment by Komari-Koshigaya** [comment]
@mengchaoheng 
你的模板挺好用的  就不换了
![1A2L{B}FUPY008~ 20I014A](https://user-images.githubusercontent.com/39209375/155725425-de23354f-6ad9-48c9-a539-800e6b870dc6.png)

你删掉的那个pdf我看也是有这问题的，
不在目录里链接目录 但是在书签中链接到目录的方法我已经找到了，可见[solution](https://github.com/sjtug/SJTUThesis/issues/165)
现在只需要找到目录链接目录是哪里导致的 把它去掉就好了

**Comment by mengchaoheng** [comment]
> @mengchaoheng 你的模板挺好用的 就不换了 ![1A2L{B}FUPY008~ 20I014A](https://user-images.githubusercontent.com/39209375/155725425-de23354f-6ad9-48c9-a539-800e6b870dc6.png)
> 
> 你删掉的那个pdf我看也是有这问题的， 不在目录里链接目录 但是在书签中链接到目录的方法我已经找到了，可见[solution](https://github.com/sjtug/SJTUThesis/issues/165) 现在只需要找到目录链接目录是哪里导致的 把它去掉就好了

“你删掉的那个pdf我看也是有这问题的”——指的是什么？解决办法我尽快吧，我最近忙一篇论文，周一截稿。今年送审是什么时间？我争取学校送审之前尽可能联系使用了模板的人。我应该是某个版本把他给改了bug进去。我的毕业论文是没有的，具体还不清楚。

想起来你说的pdf就是scutthesis.pdf吧，那个我还是加上吧，省的大家还要编译一下才出现。我此次更新就是把编译的中间文件删掉。

**Comment by mengchaoheng** [comment]
> @mengchaoheng 你的模板挺好用的 就不换了 ![1A2L{B}FUPY008~ 20I014A](https://user-images.githubusercontent.com/39209375/155725425-de23354f-6ad9-48c9-a539-800e6b870dc6.png)
> 
> 你删掉的那个pdf我看也是有这问题的， 不在目录里链接目录 但是在书签中链接到目录的方法我已经找到了，可见[solution](https://github.com/sjtug/SJTUThesis/issues/165) 现在只需要找到目录链接目录是哪里导致的 把它去掉就好了

你可以用这个模板：https://github.com/mengchaoheng/SCUTthesis-mengchaoheng。模板本来就是来自这里的。有问题随时联系我，我尽快搞定。

**Comment by mengchaoheng** [comment]
> @mengchaoheng 你的模板挺好用的 就不换了 ![1A2L{B}FUPY008~ 20I014A](https://user-images.githubusercontent.com/39209375/155725425-de23354f-6ad9-48c9-a539-800e6b870dc6.png)
> 
> 你删掉的那个pdf我看也是有这问题的， 不在目录里链接目录 但是在书签中链接到目录的方法我已经找到了，可见[solution](https://github.com/sjtug/SJTUThesis/issues/165) 现在只需要找到目录链接目录是哪里导致的 把它去掉就好了

我把我论文里的.cls文件替换到本项目，就没有这个问题了。但实际使用的时候不要这样用，因为有可能会和我的其他更新冲突，可以暂时使用
https://github.com/mengchaoheng/SCUTthesis-mengchaoheng

的模板。我这几天尽快解决这个问题。

**Comment by Komari-Koshigaya** [comment]
> 想起来你说的pdf就是scutthesis.pdf吧，那个我还是加上吧，省的大家还要编译一下才出现。我此次更新就是把编译的中间文件删掉。

毕业了还要写论文吗 那你先忙吧  倒不是很急 3月底都行

**Comment by mengchaoheng** [comment]
> > 想起来你说的pdf就是scutthesis.pdf吧，那个我还是加上吧，省的大家还要编译一下才出现。我此次更新就是把编译的中间文件删掉。
> 
> 毕业了还要写论文吗 那你先忙吧 倒不是很急 3月底都行

我的工作也是写论文。。。惨，我3-1截稿，完事再搞这个。我知道什么时候出现这个问题了，就是21年9月份那次更新，我师兄写博士毕业论文需要加功能，我那会我把.slc文件加了bug进去。在scutthesis.cls文件192-193行：
\captionsetup[subfloat]{captionskip=6bp,nearskip=0bp,farskip=0bp,topadjust=0bp,
  justification=centering,labelformat=brace,labelsep=space,subrefformat=subparens,listofformat=parens}%要使分图题和图题一样字号，选项加上 font={capFont}

===============
原来用：
\captionsetup[subfloat]{captionskip=6bp,nearskip=0bp,farskip=0bp,topadjust=0bp,justification=centering}

所以上一届的同学是没问题的，吓死我了。
但至于怎么解决我也还不清楚，我甚至忘了当时为什么加这个。暂时放下，再研究下去地铁关门了。下班。。。。。。

**Comment by mengchaoheng** [comment]
我回滚了一下历史版本，发现这个问题很严重，第一个版本就存在了。一开始我还没意识到您说的意思。我考虑暂时在readme说明一下让大家先使用scutthesis-mengchaoheng。后面修复之后再说吧。

**Comment by mengchaoheng** [comment]
已经更新，还望帮忙找找看有没有其他bug @Komari-Koshigaya

**Comment by Komari-Koshigaya** [comment]
目录显示正常了![image](https://user-images.githubusercontent.com/39209375/155843585-261282c8-d580-4d98-bbf6-00a11806919b.png)没看错的话就是加个`[nottoc]`吧

有问题会再提issue的

**Comment by mengchaoheng** [comment]
> 目录显示正常了![image](https://user-images.githubusercontent.com/39209375/155843585-261282c8-d580-4d98-bbf6-00a11806919b.png)没看错的话就是加个`[nottoc]`吧
> 
> 
> 
> 有问题会再提issue的

对，说来搞笑，我当初还是特地学习这个包，专门研究目录里包含目录项怎么加上去的。现在才知道本来就不应该有，哈哈多此一举了。时间太长还有点忘记了。

**Comment by mengchaoheng** [comment]
旧事重提，现在好像并没有实现“不在目录里链接目录 但是在书签中链接到目录“，我把[nottoc]加上之后，目录直接没有了。我得好好看看你发的链接。

**Comment by mengchaoheng** [comment]
已解决。我之前一直没加上
````
\pdfbookmark{\contentsname}{toc}
```
> 83270e989be728b6cb95919be66ca04bf3aece0b
