### ISSUE TITLE
引用的问题

### ISSUE THREAD

**Issue by SherlockHolmes221** [mengchaoheng/SCUT_thesis#31]
第一次是编译成功的，第二次改了正文内容，运行xelatexmk报错了，删除了编译生成的文件还是这样，请教一下是什么问题？
引用的文件没改
Latexmk: Missing bbl file 'scutthesis.bbl' in following:
 No file scutthesis.bbl.
Latexmk: ====List of undefined refs and citations:
  Citation 'chao2018learning' on page 2 undefined on input line 30
  Citation 'gao2018ican' on page 2 undefined on input line 31
  Citation 'wang2019deep' on page 2 undefined on input line 32
  Citation 'fang2018pairwise' on page 2 undefined on input line 35
  Citation 'li2019transferable' on page 2 undefined on input line 36
  Citation 'wan2019pose' on page 2 undefined on input line 37
  Citation '_' on page 4 undefined on input line 5
 And 32 more --- see log file.
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
Latexmk: Getting log file 'scutthesis.log'
Latexmk: Examining 'scutthesis.fls'
Latexmk: Examining 'scutthesis.log'
Latexmk: Index file 'scutthesis.idx' was written
Latexmk: References changed.
Latexmk: References changed.
Latexmk: References changed.
Latexmk: Log file says output to 'scutthesis.xdv'
Latexmk: Summary of warnings from last run of *latex:

**Comment by mengchaoheng** [comment]
建议您找个翻译软件看一的这里面的提示，根据提示来进行排除法找错误原因。我猜测它是参考文献的bib文件没有你cite引用的文章。希望这种问题试着自己解决一下，我每天都回答这样的问题的话24小时不需要睡觉了😂

**Comment by mengchaoheng** [comment]
实在不行就有texstudio好一些，有各种详细的提示以及环境快捷键，vscode对一些同学不是很友好。

**Comment by mengchaoheng** [comment]
提前把使用文档看一下，最好找个同学一起交流一下latex的一下使用方法，祝写作顺利 @SherlockHolmes221

**Comment by mengchaoheng** [comment]
解决了吗？@SherlockHolmes221

**Comment by SherlockHolmes221** [comment]
sloved
