### ISSUE TITLE
overleaf字体问题

### ISSUE THREAD

**Issue by SherlockHolmes221** [mengchaoheng/SCUT_thesis#33]
我发现overleaf导出的pdf字体大小有点偏差，比如宋体12，overleaf转出来是11.96，请问这种能解决吗？谢谢
好像不是overleaf的问题，是latex出来都这样，这个不影响过审是吗

**Comment by note286** [comment]
`72.27pt=72bp`，所以`12pt=11.9551681196bp`。

**Comment by SherlockHolmes221** [comment]
哦哦 怪不得 需要设置成严格的12吗

**Comment by note286** [comment]
不必。

**Comment by SherlockHolmes221** [comment]
好的谢谢

**Comment by note286** [comment]
你可以查看 [tex core - Globally redefining 1 pt to 1/72 in (PostScript point) and other similar changes - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/21758/globally-redefining-1-pt-to-1-72-in-postscript-point-and-other-similar-changes) 和 [tex core - Why does a TeX point differ from a Desktop Publishing point? - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/200934/why-does-a-tex-point-differ-from-a-desktop-publishing-point) 了解更多。

**Comment by sikouhjw** [comment]
这是因为
https://github.com/mengchaoheng/SCUT_thesis/blob/a225bf8fe35bf606ed718557eb199e43e47fd97b/scutthesis.cls#L33
实际上用 `ctexbook` 的话，直接 `zihao=-4` 就搞定了
