### ISSUE TITLE
总结页以奇数页结尾问题

### ISSUE THREAD

**Issue by CaiWZ** [mengchaoheng/SCUT_thesis#34]
请问一下大佬，总结页结尾是奇数页，由于页眉设置会多一个空白页。但是页码和参考文献是连续的，如何确保删除空白后页码不断呢，谢谢！\setcounter{page}{58}我把它放在了\backmatter后确实让我的空白页58不见了，但是57页会直接变成58页，少了一页。感谢大佬的解答

**Comment by note286** [comment]
学位论文是要双面打印的，每一章都是要奇数页开始，就是右手边，你随便找本书翻翻就知道咋回事了。

**Comment by CaiWZ** [comment]
好的，感谢大佬!

**Comment by JunweiH1996** [comment]
> 学位论文是要双面打印的，每一章都是要奇数页开始，就是右手边，你随便找本书翻翻就知道咋回事了。

![1](https://github.com/mengchaoheng/SCUT_thesis/assets/128341024/28fbd2f0-b45b-48f1-9ffb-b2f6483b85e5)

现在要求好像是不能出现空白页，是不是章节也可以从偶数页开始呢（本章小结在奇数页的情况）

**Comment by mengchaoheng** [comment]
1.全文内容不出现空白页好理解，正文前面单面打印的一些地方有时候需要空白页。你没有打印店也给你补上@JunweiH1996

2."总结页结尾是奇数页，由于页眉设置会多一个空白页。但是页码和参考文献是连续的，如何确保删除空白后页码不断呢?"虽然是很早的话题，但我并不太清楚具体怎么回事。最新的情况可以图文并貌解释吗？

**Comment by mengchaoheng** [comment]
> 是不是章节也可以从偶数页开始呢（本章小结在奇数页的情况）

我看到好像奇偶页开始都有呀？抱歉我还没定位到问题

**Comment by JunweiH1996** [comment]
> > 是不是章节也可以从偶数页开始呢（本章小结在奇数页的情况）
> 
> 我看到好像奇偶页开始都有呀？抱歉我还没定位到问题

看到最近两年的论文有些是参考文献和结论展望是从偶数页开始的，学校应该是不强制每一章都从偶数页开始吧（除了第一章）

**Comment by mengchaoheng** [comment]
> 看到最近两年的论文有些是参考文献和结论展望是从偶数页开始的
我看了我实验室的，并没有这个规律，您这属于幸存者偏差。@JunweiH1996 

> 学校应该不强制每一章都从奇数页开始吧

记忆中从未听说过这种说法。

**Comment by sikouhjw** [comment]
研究生学位论文撰写规范[^1]中提到：
> 论文主体分章节撰写，每章应另起一页。

> 全文通过附件形式上传（无需在表单中粘贴），论文的全文必须合并为一个完整的（从封面到致谢，全文内容不要出现空白页）PDF 文档提交，不要将各章节的多个文件压缩成一个压缩包上传，否则不予通过。

可以得出结论，章节不需要从奇数页开始。

[^1]: https://www2.scut.edu.cn/_upload/article/files/f6/1a/fa5d43a14c2a8d12e543a0ab87e3/45dcef8e-d789-4496-9bd8-ae37dd21dc89.pdf

**Comment by JunweiH1996** [comment]
谢谢大佬们的解答
