### ISSUE TITLE
标题换行页眉不换行的问题

### ISSUE THREAD

**Issue by Droliven** [mengchaoheng/SCUT_thesis#37]
![image](https://user-images.githubusercontent.com/37187316/225244214-56c00e08-04a1-4525-86fe-b89305385b89.png)

像这种情况，怎么样才能将标题换行，页眉不换行，试了 \\\\ 好像页眉会跟着换行

**Comment by mengchaoheng** [comment]
这是个好问题，要求助一下其他人

**Comment by jiankychen** [comment]
标题会自动换行，页眉不会自动换行

例如：
```
\chapter{基于多尺度残差图卷积网络的确定性人体动作预测}

\newpage

\section{引言}
```

对应的效果：
![image](https://user-images.githubusercontent.com/51186877/225803386-11bff3b0-1106-4c36-9221-5215d3101ac0.png)
以及
![image](https://user-images.githubusercontent.com/51186877/225803395-bda7dcb6-98b5-4094-83ff-cc451d600db8.png)

**Comment by Droliven** [comment]
我知道标题是流动的，一行满了自然会挤到下一行。而页眉字体比较小，一行能放得下，当然不会换行。
但事实上，如上图所示，标题自动换行的结果一行字太多，一行太少，很丑陋，所以希望寻找一种可控的换行方法。

**Comment by Droliven** [comment]
楼主的图片跟我的图片一模一样。
我知道标题是流动的，一行满了自然会挤到下一行。而页眉字体比较小，一行能放得下，当然不会换行。
但事实上，如上图所示，标题自动换行的结果一行字太多，一行太少，很丑陋，所以希望寻找一种可控的换行方法。

**Comment by note286** [comment]
@mengchaoheng 你抽空看一下，我懒得去看你的代码了，我给个`book.cls`的示例吧，你照着弄一下，关键就是利用`\markboth{}{}`，设置第一个参数即可。

```latex
\documentclass{book}
\usepackage{fancyhdr}
\fancypagestyle{plain}{
\pagestyle{fancy}
\fancyhf{}
\fancyhead[CE]{test}
\fancyhead[CO]{\leftmark}
}
\pagestyle{plain}
\usepackage{lipsum}
\begin{document}
\chapter{title1}
\lipsum[1-20]
\chapter{title2\\title2}
\markboth{\MakeUppercase{\chaptername~\thechapter.~title2--title2}}{}
\lipsum[1-20]
\chapter{title3}
\lipsum[1-20]
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/225836727-81026e0b-ce75-46b8-8307-01f8636c79bd.png)
![image](https://user-images.githubusercontent.com/16207292/225836793-0e71484c-b9eb-4e84-8b38-8490912f64a1.png)

**Comment by mengchaoheng** [comment]
抱歉实在没时间做这个修改。但我有一个疑问，一个章的标题真的需要这么长吗？考虑简称/缩写或者其他手段缩短标题？

**Comment by Droliven** [comment]
OK



| |
levondang
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月18日 01:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mengchaoheng/SCUT_thesis] 标题换行页眉不换行的问题 (Issue #37) |

抱歉实在没时间做这个修改。但我有一个疑问，一个章的标题真的需要这么长吗？考虑简称/缩写或者其他手段缩短标题？

**Comment by sikouhjw** [comment]
1. 参考 https://github.com/stone-zeng/fduthesis/commit/c1f9e3e24377e8822953f09a4e3f41582f19ae38 处理 `\\`
2. 用 `\chapter[]{}`
    ```tex
    \documentclass{book}
    \begin{document}
    \tableofcontents
    \chapter[test1]{test2}
    \newpage
    test
    \end{document}
    ```
