### ISSUE TITLE
参考文献跳转异常，目录中点击参考文献跳转到结论

### ISSUE THREAD

**Issue by Komari-Koshigaya** [mengchaoheng/SCUT_thesis#4]
参考文献跳转异常，不论是在书签还是在目录，点击“参考文献”跳转的不是对应的文献引用，而是“结论”章节。
其他章节都跳转正常
![image](https://user-images.githubusercontent.com/39209375/155844382-a549aa30-a5d3-4a00-912c-3fbdcb648fa3.png)
![image](https://user-images.githubusercontent.com/39209375/155844440-e0814cfc-0ec3-43d9-ac36-021f1d370afe.png)

我看北交的模板 点击参考文献跳转的地方也是参考文献

**Comment by mengchaoheng** [comment]
换回原来目录包含目录的版本呢？这个问题还好，至少显示正常（格式审核能通过）。

**Comment by Komari-Koshigaya** [comment]
> 换回原来目录包含目录的版本呢？这个问题还好，至少显示正常（格式审核能通过）。

换回原来的版本 这个问题还有 
是的 有空的时候看下能不能改吧🤣

**Comment by mengchaoheng** [comment]
> > 换回原来目录包含目录的版本呢？这个问题还好，至少显示正常（格式审核能通过）。
> 
> 
> 
> 换回原来的版本 这个问题还有 
> 
> 是的 有空的时候看下能不能改吧🤣

看来是老bug了，这个应该是我更改其他模板，转而使用biber带来的。当时我确实没测试过跳转正不正常，光顾着看显示正不正常了。

**Comment by Komari-Koshigaya** [comment]
@mengchaoheng 我找到解决办法了 [参考](https://blog.csdn.net/weixin_34204057/article/details/91812554)
在 “\addcontentsline{toc}{chapter}{参考文献}	%目录中添加参考文献”（scutthesis.tex lin89）前面加入`\phantomsection`即可

**Comment by mengchaoheng** [comment]
> @mengchaoheng 我找到解决办法了 [参考](https://blog.csdn.net/weixin_34204057/article/details/91812554)
> 
> 在 “\addcontentsline{toc}{chapter}{参考文献}	%目录中添加参考文献”（scutthesis.tex lin89）前面加入`\phantomsection`即可

👍，好，我这两天看看再加上去更新。
