### ISSUE TITLE
关于标题前后距离的问题

### ISSUE THREAD

**Issue by egg-ivory** [mengchaoheng/SCUT_thesis#41]
目前学习规范要求为：
2.2.1 页边距及行距
学位论文的页面边距上下左右各为25mm
**章、节、条三级标题为单倍行距，段前、段后各设为0.5行（即前后各空0.5行）**
正文为1.5倍行距，段前、段后无空行（即空0行）

也就是说，模板要求的标题前后句一致，如下：
![1680665658714](https://user-images.githubusercontent.com/33169829/229974728-86c64d62-af3f-473b-9ee1-1ee962af09df.png)

目前我对cls文件进行了修改
![1680665714995](https://user-images.githubusercontent.com/33169829/229974858-278cbb3d-0e46-4421-9677-856a282014cc.png)
但我只是凭感觉调的，没有进行精确计算，所以各位不要直接使用。目前我的困难是不知道怎么计算和设置数值合适，发出来和大家交流交流

**Comment by egg-ivory** [comment]
补充一下，这里的前后距离，指的是标题到上下段的距离，即word里的行距

**Comment by nebulaed** [comment]
```
\setlength{\parskip}{0ex}% 正文段前段后距：无空行
\titlespacing{\chapter}{0pt}{-20pt}{10pt} % 缩短章标题上间距，revised by Quansheng Guan
\titlespacing{\section}{0pt}{0pt}{12pt}  % 标题间距
\titlespacing{\subsection}{0pt}{4pt}{12pt}
```
这是我的，感觉也不是很准，在标题和正文上下相邻的时候仔细比对过差不多，但是当标题上下相邻间距就太大了，比如3.4和3.4.1间标题间距就太大

**Comment by nebulaed** [comment]
> ```
> \setlength{\parskip}{0ex}% 正文段前段后距：无空行
> \titlespacing{\chapter}{0pt}{-20pt}{10pt} % 缩短章标题上间距，revised by Quansheng Guan
> \titlespacing{\section}{0pt}{0pt}{12pt}  % 标题间距
> \titlespacing{\subsection}{0pt}{4pt}{12pt}
> ```
> 
> 这是我的，感觉也不是很准，在标题和正文上下相邻的时候仔细比对过差不多，但是当标题上下相邻间距就太大了，比如3.4和3.4.1间标题间距就太大

节三级标题\subsubsection因为我没用到所以没管行距
