### ISSUE TITLE
类似 MS Word 的孤行控制功能

### ISSUE THREAD

**Issue by SYL66** [mengchaoheng/SCUT_thesis#43]
目前在使用模板过程中发现并没有对 widows（段落的首行在一页的尾行或段落的尾行在一页的首行）进行控制，希望可以添加类似 MS Word 的孤行控制功能，具体可以参考下面的链接：[Prevent new page if new line is only a few words](https://tex.stackexchange.com/questions/558238/prevent-new-page-if-new-line-is-only-a-few-words)

**Comment by sikouhjw** [comment]
`texdoc xeCJK`, `\xeCJKsetup{CheckSingle=true}`

**Comment by SYL66** [comment]
> `texdoc xeCJK`, `\xeCJKsetup{CheckSingle=true}`

感谢告知，这是我未有注意到的孤字控制。xeCJK 文档里提到 CheckSingle 设置只能控制孤字，并不能控制孤行，这与我的实践发现是一致的。另外，我未在文档里发现有关实现孤行控制的设置。

**Comment by sikouhjw** [comment]
> 感谢告知，这是我未有注意到的孤字控制。xeCJK 文档里提到 CheckSingle 设置只能控制孤字，并不能控制孤行，这与我的实践发现是一致的。另外，我未在文档里发现有关实现孤行控制的设置。

看错问题了，孤行控制比较麻烦，尤其是涉及浮动体和公式时，建议在终稿时手动修改文本。

**Comment by SYL66** [comment]
> > 感谢告知，这是我未有注意到的孤字控制。xeCJK 文档里提到 CheckSingle 设置只能控制孤字，并不能控制孤行，这与我的实践发现是一致的。另外，我未在文档里发现有关实现孤行控制的设置。
> 
> 看错问题了，孤行控制比较麻烦，尤其是涉及浮动体和公式时，建议在终稿时手动修改文本。

好的，非常感谢！
