### ISSUE TITLE
摘要页编码错误

### ISSUE THREAD

**Issue by Cemlau** [mengchaoheng/SCUT_thesis#45]
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/135103839/3d499e59-f810-4f56-9b2d-bacc6ea655b2)
所有的编译环境与PDF相同
2020 texlive
texstudio
求解决
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/135103839/773380ae-58c1-432c-a2b5-97072e5525c5)

**Comment by mengchaoheng** [comment]
没看懂错误在哪里

**Comment by Cemlau** [comment]
> 没看懂错误在哪里

有些字符串显示一直错误，字母d

**Comment by Cemlau** [comment]
字体也安装了，找不到原因

**Comment by mengchaoheng** [comment]
你这个是下载下来没改过然后编译我的模版说明吗？不应该有错误，如果你移动了位置，你把引用删掉，你写点其他东西看看。要确保编译选项和bib文件路径正确。实在不行百度一下自己哪里环境有问题。你最好把编译错误贴一下

**Comment by Cemlau** [comment]
> 你这个是下载下来没改过然后编译我的模版说明吗？不应该有错误，如果你移动了位置，你把引用删掉，你写点其他东西看看。要确保编译选项和bib文件路径正确。实在不行百度一下自己哪里环境有问题。你最好把编译错误贴一下

我试试，我是直接下载，用texstudio编译就一直这样显示

**Comment by mengchaoheng** [comment]
那你编译选项要选对，应该就没问题。除非我更新后搞乱了什么东西，不过可能性很小

**Comment by sikouhjw** [comment]
> 我试试，我是直接下载，用texstudio编译就一直这样显示

https://github.com/mengchaoheng/SCUT_thesis/blob/a225bf8fe35bf606ed718557eb199e43e47fd97b/abstract.tex#L4-L9
你说的是错的，你修改了内容。

请不要拿『我什么都没做，好端端的人没了』这种套话来尝试解决问题

**Comment by Cemlau** [comment]
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/135103839/a6e01df2-480e-4184-a0a2-88032d616d6b)

**Comment by mengchaoheng** [comment]
@sikouhjw 作为开发者外喜欢你的作风，作为同学，大家还是客气一点，哈哈哈。没事，好事多磨。

**Comment by Cemlau** [comment]
> > 我试试，我是直接下载，用texstudio编译就一直这样显示
> 
> https://github.com/mengchaoheng/SCUT_thesis/blob/a225bf8fe35bf606ed718557eb199e43e47fd97b/abstract.tex#L4-L9
> 
> 
> 你说的是错的，你修改了内容。
> 请不要拿『我什么都没做，好端端的人没了』这种套话来尝试解决问题

我试过没改的，也是如此，我可以运行截图给你，这个改动是为了测试是否是格式错误导致的编码出错

**Comment by Cemlau** [comment]
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/135103839/42f1de77-12d5-44f9-b8ed-4512ea0b70ec)

**Comment by Cemlau** [comment]
每个字母d显示出错，其余都正常

**Comment by Cemlau** [comment]
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/135103839/dfdc0d97-36ed-4e89-aa20-1c72e0e9fa7b)

**Comment by Cemlau** [comment]
在VScode上运行也是同样，字母d显示错误

**Comment by sikouhjw** [comment]
上传用 xelatex 编译后的 log 文件

**Comment by mengchaoheng** [comment]
原谅我还是不懂“字母d显示错误”是什么意思

**Comment by Cemlau** [comment]
> 上传用 xelatex 编译后的 log 文件

已传，您看一下

**Comment by sikouhjw** [comment]
估计是发行版版本的问题，texlive 2020 有点老，建议用最新的

**Comment by Cemlau** [comment]
> 估计是发行版版本的问题，texlive 2020 有点老，建议用最新的

2022也是同样的输出结果，个人感觉像是KeywordsEN和KeywordsCN命令内部的字体设置可能有点问题

**Comment by sikouhjw** [comment]
https://github.com/mengchaoheng/SCUT_thesis/blob/a225bf8fe35bf606ed718557eb199e43e47fd97b/scutthesis.cls#L152-L155
你改下这两处的代码吧，其实只需要 `\zihao{-4}` 就可以的

**Comment by Cemlau** [comment]
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/135103839/8d94d259-5650-4b10-98db-c157675b8b3d)

**Comment by sikouhjw** [comment]
> > https://github.com/mengchaoheng/SCUT_thesis/blob/a225bf8fe35bf606ed718557eb199e43e47fd97b/scutthesis.cls#L152-L155
> > 
> > 你改下这两处的代码吧，其实只需要 `\zihao{-4}` 就可以的
> 
> 这个我不太明白，我认为是字体的设置可能重复了，也许对同一个对象定义了两种不同的字体？导致输出的时候原本应该显示为d的字符显示为phi, 修改了字体大小，仍然解决不了

我的意思是，这些代码都是冗余的代码，只需要 `\zihao{-4}` 就可以了

**Comment by Cemlau** [comment]
> 
您能明确指出是哪里替换成\zihao{-4}吗？

**Comment by sikouhjw** [comment]
```tex
\newcommand{\abskeyscn}{\xiaosihao}
\newcommand{\abskeysen}{\xiaosihao}
```

**Comment by mengchaoheng** [comment]
各种字体问题可以考虑使用texleaf？

**Comment by Cemlau** [comment]
问题已解决
导言区补充：
\usepackage{times}
\usepackage[T1]{fontenc}

**Comment by mengchaoheng** [comment]
所以不是字体问题吗？我用过win用过macOS，都没有这个编码错误问题，所以一下子也不知道怎么解决（因为没法复现问题）。感谢您的补充。

**Comment by Cemlau** [comment]
> 所以不是字体问题吗？我用过win用过macOS，都没有这个编码错误问题，所以一下子也不知道怎么解决（因为没法复现问题）。感谢您的补充。

有一个新的需求，当封面页文件更换为页数小于8页的PDF时，如何去除空白页呢？
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/135103839/45656877-f740-429a-a967-e09ef7696592)

**Comment by mengchaoheng** [comment]
> 当封面页文件更换为页数小于8页的PDF时，如何去除空白页呢？

封面文件单独用word改，然后，替换的位置看替换设置[代码](https://github.com/mengchaoheng/SCUT_thesis/blob/7be6e77dcf6009c6c83ce8d7a792dcf3ec3e3ca9/scutthesis.cls#L423)，需要理解一下代码然后照着葫芦画瓢。例如需要百度理解一下`\includepdf[pages={1-5,{},7-8}]{thesis_cover.pdf}`的pages选项的含义。
