### ISSUE TITLE
需要修改一下封面校徽年份，以及摘要到目录页码字体大小

### ISSUE THREAD

**Issue by york-yan** [mengchaoheng/SCUT_thesis#46]
毕业论文顺利通过审查，感谢作者对于该项目的维护，可比写word省事多了。

在审查中发现，封面校徽今年改了，以前是1934年，现在加到了1918年，摘要到目录的罗马字体页码的字号为五号，现在的那个要稍微大一点，磅数是11.几，五号字体是10.46，我在电子版审查的时候因为这俩问题被打回来修改了一下。

**Comment by mengchaoheng** [comment]
就是页码大了是吗？需要改标准五号？所以您是怎么解决的，可不可以分享此段代码？

**Comment by york-yan** [comment]
-------自动回复 ------
您好，来信已收到，我会尽快处理。祝工作顺利！

**Comment by york-yan** [comment]
我用了最简单的方法手动在PDF里面编辑修改的，因为离校了，电脑是实验室的资产，没法用代码修改。我觉得应该是在字号那改一下，回头安顿好了我再看看。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MCH ***@***.***&gt;
发送时间: 2023年7月2日 21:31
收件人: mengchaoheng/SCUT_thesis ***@***.***&gt;
抄送: yorkkk ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [mengchaoheng/SCUT_thesis] 需要修改一下封面校徽年份，以及摘要到目录页码字体大小 (Issue #46)





 
就是页码大了是吗？需要改标准五号？所以您是怎么解决的，可不可以分享此段代码？

**Comment by sikouhjw** [comment]
> 摘要到目录的罗马字体页码的字号为五号，现在的那个要稍微大一点，磅数是11.几，五号字体是10.46，我在电子版审查的时候因为这俩问题被打回来修改了一下。

在 latex 中：
- 五号字=10bp
- 小四号字=12bp
- bp≠pt

请你确认单位后再来进行讨论

**Comment by mengchaoheng** [comment]
> 在审查中发现，封面校徽今年改了，以前是1934年，现在加到了1918年，

回头看这个问题，对于这件事，我只能说，无语。学什么不好，学某些985高校改建校年份，校庆都乱了。大家自行下载学校给的最新封面即可。

**Comment by york-yan** [comment]
-------自动回复 ------
您好，来信已收到，我会尽快处理。祝工作顺利！
