### ISSUE TITLE
正文引用问题

### ISSUE THREAD

**Issue by JeremyLinky** [mengchaoheng/SCUT_thesis#49]
感谢作者大大的贡献。

我在使用overleaf写毕业论文，有以下问题，希望作者大大有时间可以回复下：

1、正文所有的引用都是有颜色的，要么蓝色要么红色，请问这个是允许的吗？我看往届师兄的论文都是黑色的
2、参考文献在文中的引用是正常字体还是右上角小字体？

**Comment by mengchaoheng** [comment]
颜色按照注释提示进行更改。字体不需要改，具体是什么字体我得看一看，我也不记得了。

**Comment by JeremyLinky** [comment]
感谢 就是我看到往届师兄论文都是这样引用的：
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/50053052/5799adca-5797-4fb7-939f-a2054ebce620)
在右上角，但是咱们这个github的引用是这样的：
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/50053052/f595f7c2-8de5-4553-b993-9052b4dd6c40)
到底哪一种才是正确的？还是说都可以？

**Comment by note286** [comment]
你不要看往届的，你先去查一下学校对此的规范是啥。

**Comment by mengchaoheng** [comment]
讲道理，送审的时候也可以是彩色引用，看着更酷一些，我自己审过学位论文，相信很多审稿人和我一样喜欢看有颜色的文献和图表引用，最终提交给学校图书馆的那个版本改回黑色即可。

**Comment by mengchaoheng** [comment]
改这个颜色就行了。你看一下GitHub这个版本代码的注释，可能overleaf那边的代码注释没写清楚，具体我没注意看

**Comment by mengchaoheng** [comment]
> 感谢 就是我看到往届师兄论文都是这样引用的：
> 
> ![image](https://github.com/mengchaoheng/SCUT_thesis/assets/50053052/5799adca-5797-4fb7-939f-a2054ebce620)
> 
> 在右上角，但是咱们这个github的引用是这样的：
> 
> ![image](https://github.com/mengchaoheng/SCUT_thesis/assets/50053052/f595f7c2-8de5-4553-b993-9052b4dd6c40)
> 
> 到底哪一种才是正确的？还是说都可以？

这两种有不同的方法写，根据需要使用，具体在使用说明里有，你可以再看看

**Comment by JeremyLinky** [comment]
感谢。我把colorlinks设置为false后发现还是有颜色，您能再具体说下要怎么改参数么

**Comment by JeremyLinky** [comment]
哦我看到了，感谢感谢

**Comment by mengchaoheng** [comment]
SCUTThesis.tex文件37行和38行。

**Comment by note286** [comment]
https://github.com/mengchaoheng/SCUT_thesis/blob/7a67b0d958ca0ab9f9bc105e9adc42eb9e8e0c09/scutthesis.tex#L37-L38
