### ISSUE TITLE
草稿封面中加校外导师（不是很难，初学者可以看看）

### ISSUE THREAD

**Issue by moonhangest** [mengchaoheng/SCUT_thesis#51]
由于本人需要和校外导师讨论，有时候觉得在草稿封面加上ta的名字会好点，于是在gpt的建议下，我在.cls文件中进行了部分修改，达到草稿封面可以出现两行导师信息的效果（首行为校内导师，第二行为校外导师），具体如下：
1，在cls文件的第41行改为：\def \supervisor#1#2{\gdef\@supervisor{#1}\gdef\@supervisorB{#2}}  %加校外导师；
2，在cls文件中的第447行开始修改为：
\centerline{\songti\erhao   {\@supervisor} }
\vskip 0.5em  %间隔放宽点
\centerline{\songti\erhao   {\@supervisorB} }  %第二个导师的文字格式
3，在正文tex中第53行，改为：
\supervisors{Dr. Smith}{Prof. Johnson}即可。

**Comment by mengchaoheng** [comment]
可能这算比较小众的需求？辛苦您了，感谢分享方案。
