### ISSUE TITLE
子图标题双括号怎么弄呀？

### ISSUE THREAD

**Issue by moonhangest** [mengchaoheng/SCUT_thesis#52]
大家新年好，我想问下：我现在想直接按照双括号来编辑，因为看了以往学院的论文，都是双括号就行。然而文件中是单括号的，我尝试调整一下，但还是失败了。。。希望有知道的大佬不吝分享，感谢感谢！！

**Comment by mengchaoheng** [comment]
可以图文并茂解释一下你的需求吗？没太听懂

**Comment by moonhangest** [comment]
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/125921474/8bdd3da7-553b-45a0-abb7-9c301ca1bdc2)
如图：我想将子图的标题序号改为（a），（b）。。。请问怎么改？
![1](https://github.com/mengchaoheng/SCUT_thesis/assets/125921474/122508a2-bc5b-4fe1-a78a-c0fade2f0fa5)

**Comment by moonhangest** [comment]
谢谢是这里的问题。
我后来尝试了几种修改，比如添加括号之类，但发现要么子图显示了双括号，但正文引用处是’‘((xxxx))''的模式。有点麻烦。
最后稍微另寻网上分享的经验，发现可以了！
具体如下：

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 根据子图引用显示，重定义部分参数 ——by mch
\captionsetup[subfigure]{labelformat=simple, labelsep=space}
\renewcommand\thesubfigure{(\alph{subfigure})}
\DeclareSubrefFormat{parens}{#1 #2}
\DeclareSubrefFormat{subparens}{#2}
\DeclareCaptionListOfFormat{parens}{#1 #2}
\DeclareCaptionListOfFormat{subparens}{#2}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

就是把原来语句中的括号全部去掉，并在前面加入两个命令语句即可。
在此感谢！！

**Comment by mengchaoheng** [comment]
是的，改了格式之后，还需要对文中引用进行更改，我太久没看代码忘记在哪操作，大概就是照着葫芦画瓢。由于每个人审美不同，需要的效果不同。我最初是在学校格式要求下，根据实验室的同学认可的风格进行自由发挥，得到本项目的版本。但凡需要微调的，都需要大家diy一下。感谢分享您的方案。我会在适当时候把大家的意见全部集成到文件中给后生自由选择风格。
