### ISSUE TITLE
英文字体在 Linux 平台出错

### ISSUE THREAD

**Issue by h-hg** [mengchaoheng/SCUT_thesis#53]
https://github.com/mengchaoheng/SCUT_thesis/blob/7a67b0d958ca0ab9f9bc105e9adc42eb9e8e0c09/scutthesis.cls#L77

这一行改成

```tex
\setmainfont[Mapping=tex-text]{Times-New-Roman.ttf}
```
出现的效果是
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/38984008/e95d187f-dcfe-412a-b32f-8182308f3aaf)

请求修复，不知道怎么修改。

**Comment by sikouhjw** [comment]
TNR 的文件名是 `times.ttf`

**Comment by h-hg** [comment]
> TNR 的文件名是 `times.ttf`

在 overleaf 分支中，只看到 `Times-New-Roman.ttf` 这个字体，没看到 times.ttf 这个，我自己从 windows C:\windows/fonts 复制出 TIMES.TTF 这个文件，改成

```tex
\setmainfont[Mapping=tex-text]{TIMES.TTF}
```

效果如下，但是没有加粗。

![image](https://github.com/mengchaoheng/SCUT_thesis/assets/38984008/1c3ea5b3-1957-4a56-8030-0c3aee6d25d6)

另外，从 windows 复制的字体有这么多，这是从中选了一个。

![image](https://github.com/mengchaoheng/SCUT_thesis/assets/38984008/cc00ebd3-2f5d-4cad-be2b-52c8a5eb4b9f)

**Comment by mengchaoheng** [comment]
字体这部分，确实需要diy一下，平台和电脑不同都不同，我也在设置文件夹给了一些字体文件。可以看看主分支。

---- 回复的原邮件 ----
| 发件人 | Hunter ***@***.***> |
| 发送日期 | 2024年02月22日 11:09 |
| 收件人 | mengchaoheng/SCUT_thesis ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [mengchaoheng/SCUT_thesis] 英文字体在 Linux 平台出错 (Issue #53) |

TNR 的文件名是 times.ttf

在 overleaf 分支中，只看到 Times-New-Roman.ttf 这个字体，没看到 times.ttf 这个，我自己从 windows C:\windows/fonts 复制出 TIMES.TTF 这个文件，改成

\setmainfont[Mapping=tex-text]{TIMES.TTF}

效果如下，但是没有加粗。

image.png (view on web)

另外，从 windows 复制的字体有这么多，这是从中选了一个。

image.png (view on web)

**Comment by h-hg** [comment]
> 字体这部分，确实需要diy一下，平台和电脑不同都不同，我也在设置文件夹给了一些字体文件。可以看看主分支。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Hunter ***@***.***> | | 发送日期 | 2024年02月22日 11:09 | | 收件人 | mengchaoheng/SCUT_thesis ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [mengchaoheng/SCUT_thesis] 英文字体在 Linux 平台出错 (Issue #53) | TNR 的文件名是 times.ttf 在 overleaf 分支中，只看到 Times-New-Roman.ttf 这个字体，没看到 times.ttf 这个，我自己从 windows C:\windows/fonts 复制出 TIMES.TTF 这个文件，改成 \setmainfont[Mapping=tex-text]{TIMES.TTF} 效果如下，但是没有加粗。 image.png (view on web) 另外，从 windows 复制的字体有这么多，这是从中选了一个。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

主分支的代码也是这个？

```tex
\setmainfont[Mapping=tex-text]{Times New Roman}%\rmfamily 使用的字体,默认英文和数字的字体。
```

**Comment by mengchaoheng** [comment]
Overleaf分支只是给在线的overleaf版本改的，为了存档新增的分支，如果您本地使用，最好用master或main主分支(我也忘了分支名)。然后按照说明书设置一下字体，字体名字正确，就可以了。

---- 回复的原邮件 ----
| 发件人 | Hunter ***@***.***> |
| 发送日期 | 2024年02月22日 11:13 |
| 收件人 | mengchaoheng/SCUT_thesis ***@***.***> |
| 抄送人 | Simon ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [mengchaoheng/SCUT_thesis] 英文字体在 Linux 平台出错 (Issue #53) |

字体这部分，确实需要diy一下，平台和电脑不同都不同，我也在设置文件夹给了一些字体文件。可以看看主分支。
…
---- 回复的原邮件 ---- | 发件人 | Hunter @.> | | 发送日期 | 2024年02月22日 11:09 | | 收件人 | mengchaoheng/SCUT_thesis @.> | | 抄送人 | Subscribed @.> | | 主题 | Re: [mengchaoheng/SCUT_thesis] 英文字体在 Linux 平台出错 (Issue #53) | TNR 的文件名是 times.ttf 在 overleaf 分支中，只看到 Times-New-Roman.ttf 这个字体，没看到 times.ttf 这个，我自己从 windows C:\windows/fonts 复制出 TIMES.TTF 这个文件，改成 \setmainfont[Mapping=tex-text]{TIMES.TTF} 效果如下，但是没有加粗。 image.png (view on web) 另外，从 windows 复制的字体有这么多，这是从中选了一个。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

主分支的代码也是这个？

\setmainfont[Mapping=tex-text]{Times New Roman}%\rmfamily 使用的字体,默认英文和数字的字体。

**Comment by sikouhjw** [comment]
> > TNR 的文件名是 `times.ttf`
> 
> 在 overleaf 分支中，只看到 `Times-New-Roman.ttf` 这个字体，没看到 times.ttf 这个，我自己从 windows C:\windows/fonts 复制出 TIMES.TTF 这个文件，改成
> 
> ```
> \setmainfont[Mapping=tex-text]{TIMES.TTF}
> ```
> 
> 效果如下，但是没有加粗。
> 
> ![image](https://private-user-images.githubusercontent.com/38984008/306841435-1c3ea5b3-1957-4a56-8030-0c3aee6d25d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTY2NzMsIm5iZiI6MTcwODY1NjM3MywicGF0aCI6Ii8zODk4NDAwOC8zMDY4NDE0MzUtMWMzZWE1YjMtMTk1Ny00YTU2LTgwMzAtMGMzYWVlNmQyNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyNDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYTg5M2JmNTRkMTgzMzc4ZmNmYTg0ZTc3ZmQ4MDI5MmJiOGNhNTFlZDYyMmNiOTkyOGE3YmJkOTFhYWI1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Du6mzN6r0TRukVhHvOd3Pknsn1mTiAFQ23HOGm4eVdE)
> 
> 另外，从 windows 复制的字体有这么多，这是从中选了一个。
> 
> ![image](https://private-user-images.githubusercontent.com/38984008/306841997-cc00ebd3-2f5d-4cad-be2b-52c8a5eb4b9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTY2NzMsIm5iZiI6MTcwODY1NjM3MywicGF0aCI6Ii8zODk4NDAwOC8zMDY4NDE5OTctY2MwMGViZDMtMmY1ZC00Y2FkLWJlMmItNTJjOGE1ZWI0YjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyNDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNzlmNmI2MDdiOWZiMDJmZDRhNTYzNjQ3NjJjNjRjODgzZWJkODBhODllNDVjNzQ3MzE0NDFlMGQxNjJiZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sME9G247LBSl6Q0XinLpRYr_WSMKFN_fA1o2bAMB1VU)

如果指定“字体文件名”设置字体，需要手动设置粗体等。如果指定“字体名”，则一般不需要。

Overleaf/Linux 平台不支持“字体名”，因此需要手动指定。手动指定粗体的代码参考 `texdoc fontspec`。
