### ISSUE TITLE
草稿封面标题过长不能自动分行

### ISSUE THREAD

**Issue by moonhangest** [mengchaoheng/SCUT_thesis#54]
如题，我尝试用’\\‘,'\protect',结果还是一行显示，而且由于字体原因，前后部分内容溢出页面。请问有人经历过并处理好了？

**Comment by sikouhjw** [comment]
https://github.com/mengchaoheng/SCUT_thesis/blob/7a67b0d958ca0ab9f9bc105e9adc42eb9e8e0c09/scutthesis.cls#L436
换成
```tex
\begingroup
\centering
\heiti\yihao  {\@title}\par
\endgroup
```

**Comment by moonhangest** [comment]
谢谢分享！已经处理好！
