### ISSUE TITLE
目录的蓝色字体颜色问题

### ISSUE THREAD

**Issue by Sigmafye** [mengchaoheng/SCUT_thesis#55]
请问怎么把目录字体的蓝色换成黑色？有朋友分享下吗

**Comment by mengchaoheng** [comment]
@Sigmafye 在说明书我有提到如何改颜色。除了最终版，其实送审带颜色也无所谓。只要是正常的颜色。我作为审稿人也会喜欢引用/超链接带颜色的。

**Comment by Sigmafye** [comment]
哇！感谢您的回复，我找到了，在scutthesis.tex里面有黑白和彩色的注释。
