### ISSUE TITLE
绪论之前多出一页空白页

### ISSUE THREAD

**Issue by JeremyLinky** [mengchaoheng/SCUT_thesis#57]
作者您好，今天检查发现，在绪论之前，也就是\mainmatter的时候，总会多出一页空白页，不知道如何消除，请问作者您知道原因和解决方法么？感谢！
![image](https://github.com/mengchaoheng/SCUT_thesis/assets/50053052/a9b00ad6-9097-491d-9e63-7747beb09b2b)

**Comment by mengchaoheng** [comment]
> 绪论之前，也就是\mainmatter的时候，总会多出一页空白页

@JeremyLinky 这可能是bug，我试了一下，好像下面两个同时用就没问题，单独用一个就有此问题。
```
\include{symbols}	% 符号对照表(可选)
\include{abbreviation} 	% 缩略词
```
并且测试发现，这两个都是基于表格做的内容，内容多了也会另起一页。这个问题我再想想办法。不过 您可以暂时不写这部分，看看能不能接受？

**Comment by mengchaoheng** [comment]
还有一个笨方法，就是生成的pdf删除掉这一页多余的，这个暂时需要更多同学帮忙修复，我最近比较忙。

**Comment by JeremyLinky** [comment]
好嘞 感谢您！

**Comment by mengchaoheng** [comment]
这里有待解决，我先记下

**Comment by JeremyLinky** [comment]
还有个问题想请教您一下，我发现我删除了目录里面的thesis_cover.pdf，他还是能编译出来，我找不到真正的thesis_cover.pdf到底放在哪里

**Comment by mengchaoheng** [comment]
> 删除了目录里面的thesis_cover.pdf，他还是能编译出来

请问使用什么编译环境？你在目录里搜索看看。cover_file文件夹存word。填好后，另存为pdf到根目录。一般是这样没问题

**Comment by JeremyLinky** [comment]
我用overleaf。cover_file文件夹只有一个readme.txt，我找遍了全部文件，都已经没有thesis_cover.pdf了，但是依旧可以编译出来。

**Comment by mengchaoheng** [comment]
overleaf版本本来就比较初级，很少在上面修复问题。他就是临时拉出来的一个分支。你得自己做好了封面文件自己上传上去。试试看能不能改

**Comment by JeremyLinky** [comment]
好的，我做好封面传上去也无效，显示找不到，明明放在根目录。。而且很奇怪，都没有thesis_cover.pdf，他居然能编译出来

**Comment by Sigmafye** [comment]
这是因为你没有注释掉scutthesis.tex里面关于封面默认设置的相关代码

**Comment by Sigmafye** [comment]
> 还有个问题想请教您一下，我发现我删除了目录里面的thesis_cover.pdf，他还是能编译出来，我找不到真正的thesis_cover.pdf到底放在哪里

这是因为你没有注释掉scutthesis.tex里面关于封面默认设置的相关代码
