### ISSUE TITLE
目录如何隐藏页眉页脚？

### ISSUE THREAD

**Issue by PositiveTom** [mengchaoheng/SCUT_thesis#58]
目录如何隐藏页眉页脚？我在scutthesis.tex的64行附近，在 	\tableofcontents的下一行增加了\thispagestyle{empty}，但是占两页的目录，第一页仍然有页码，第二页无页码
<img width="481" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/5a3c2924-b1f5-4966-b90c-ba703a55294f">
<img width="626" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/59b467f2-7c5f-4f46-9f4d-851deceb1b68">

**Comment by mengchaoheng** [comment]
现在的目录不能满足要求吗？规范和现行方案有什么区别？还是需要自定义什么功能？！@PositiveTom

**Comment by PositiveTom** [comment]
> 现在的目录不能满足要求吗？规范和现行方案有什么区别？还是需要自定义什么功能？@PositiveTom

我们老师要求目录不含有页眉页脚，她希望可以把目录的页码去掉

**Comment by mengchaoheng** [comment]
你们老师。。。

把学校规范甩给他看，他要是坚持，那就只能你们辛苦一下了。我有一个不成熟的笨方法，就是取消页码设置，然后生成的目录单独拿出来，把正常版本的pdf文件目录页用无页码的目录拼接。咱们不是为了成为latex大师，怎么省事怎么来。面对这种不正常的要求，就只能这样咯。因为你最终上交学校得按照规范啊，你不能为了老师新开发一个模版吧

目前的目录设置是：
```
%%%%%%%%%%%%%%%%%%--by MCH--%%%%%%%%%%%%%%%%%%%%%%%%%%%%2022-2-26更新
%---ref: https://blog.csdn.net/youyagaozitai/article/details/70210297?%3E
% 增加目录的项目——tocbibind
%正文区写 \tableofcontents %输出目录命令，输出内容是正文中/section等的内容。 
%若在目录中显示其他条目，使用：  
\RequirePackage[nottoc]{tocbibind} %增加目录项目，tocbibind宏包会自动加入目录项本身、参考文献、索引等项目。[nottoc]取消了对自身的显示

```
还有，这里设置了一些：

```
\renewcommand\frontmatter{ %标题之后，开始中英文摘要，目录
	\clearpage	
    \pagestyle{plain} % plain
    \pagenumbering{Roman}% Roman style page number
    \@mainmatterfalse
}
```
您看看那个可以更改出没有页码的。结合百度

**Comment by mengchaoheng** [comment]
目录这里，在前年进行过一次修改，当时查了很多资料，我现在一时半会无法对此形成清晰的认识，没法给出解决方案。

**Comment by mengchaoheng** [comment]
> 她希望可以把目录的页码去掉

我看到这句话我想吐血，希望您把我的话转给她。

**Comment by PositiveTom** [comment]
> > 她希望可以把目录的页码去掉
> 
> 我看到这句话我想吐血，希望您把我的话转给她。



> 你们老师。。。
> 
> 把学校规范甩给他看，他要是坚持，那就只能你们辛苦一下了。我有一个不成熟的笨方法，就是取消页码设置，然后生成的目录单独拿出来，把正常版本的pdf文件目录页用无页码的目录拼接。咱们不是为了成为latex大师，怎么省事怎么来。面对这种不正常的要求，就只能这样咯。因为你最终上交学校得按照规范啊，你不能为了老师新开发一个模版吧
> 
> 目前的目录设置是：
> 
> ```
> %%%%%%%%%%%%%%%%%%--by MCH--%%%%%%%%%%%%%%%%%%%%%%%%%%%%2022-2-26更新
> %---ref: https://blog.csdn.net/youyagaozitai/article/details/70210297?%3E
> % 增加目录的项目——tocbibind
> %正文区写 \tableofcontents %输出目录命令，输出内容是正文中/section等的内容。 
> %若在目录中显示其他条目，使用：  
> \RequirePackage[nottoc]{tocbibind} %增加目录项目，tocbibind宏包会自动加入目录项本身、参考文献、索引等项目。[nottoc]取消了对自身的显示
> ```
> 
> 还有，这里设置了一些：
> 
> ```
> \renewcommand\frontmatter{ %标题之后，开始中英文摘要，目录
> 	\clearpage	
>     \pagestyle{plain} % plain
>     \pagenumbering{Roman}% Roman style page number
>     \@mainmatterfalse
> }
> ```
> 
> 您看看那个可以更改出没有页码的。结合百度

好嘞，多谢，
我刚刚也查了许多资料，如果她真的这样要求，只能adobe拼接pdf了。

**Comment by PositiveTom** [comment]
> > 她希望可以把目录的页码去掉
> 
> 我看到这句话我想吐血，希望您把我的话转给她。

不敢反驳呜呜呜🥹

**Comment by mengchaoheng** [comment]
> 我师兄师姐在知网上查到的毕业论文都是目录没有页码的

是这样的，也许其他要求不一样，但下面是学校的规范：

```
2.2.3 页码
论文页码从主体部分（绪论、正文、结论）开始，直至“参考文献、附录、攻读学位期间取得的研究成果、致谢”结束，用五号阿拉伯数字编连续码，页码位于页脚居中。
封面、英文内封、提名页、原创性声明和使用授权书、答辩委员会委员签名的答辩决议书不编入页码。
摘要、目录、图表清单、主要符号表用五号罗马数字编连续码，页码位于页脚居中。

```
