### ISSUE TITLE
想请问参考文献，如何角标不在右上角？

### ISSUE THREAD

**Issue by PositiveTom** [mengchaoheng/SCUT_thesis#59]
目前的情况：
<img width="40" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/e08fb365-5836-4b64-b161-ca77dfbe2370">
我希望的样子如下：
<img width="83" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/225a09fa-45df-4fca-8f8f-9267aeab33dc">

**Comment by mengchaoheng** [comment]
请仔细看说明文件scutthesis.pdf

**Comment by PositiveTom** [comment]
我在那个文档里面ctrl+f搜索关键词，cite/参考文献/引用/上标/右上角上标，没有搜索出相关的配置说明呀，好兄弟

**Comment by PositiveTom** [comment]
> 请仔细看说明文件scutthesis.pdf


我在那个文档里面ctrl+f搜索关键词，cite/参考文献/引用/上标/右上角上标，没有搜索出相关的配置说明呀，好兄弟

**Comment by mengchaoheng** [comment]
```
然后在 tex 文件编辑界面直接粘贴，默认
的时上标形式，若需要非上标形式，可以改为\parencite{xxx}，其中 xxx 是 Citation Key。
```
也可以百度，当年我就是百度出来的。

题外话，`3.5 参考文献`里我之前写了太多zotero的东西，后续应该删掉。

**Comment by PositiveTom** [comment]
> ```
> 然后在 tex 文件编辑界面直接粘贴，默认
> 的时上标形式，若需要非上标形式，可以改为\parencite{xxx}，其中 xxx 是 Citation Key。
> ```
> 
> 也可以百度，当年我就是百度出来的。
> 
> 题外话，`3.5 参考文献`里我之前写了太多zotero的东西，后续应该删掉。

好嘞，谢谢好兄弟，解决了。主要我在网上搜到的都是upcite上标，cite平齐；这里cite上标，parencite才是平齐
