### ISSUE TITLE
figure位置的问题

### ISSUE THREAD

**Issue by PositiveTom** [mengchaoheng/SCUT_thesis#61]
figure使用htbp或者!t参数之后浮动到本章小节文字中间了，怎么强制图片在本章小节这个subsection之前

**Comment by sikouhjw** [comment]
图片只需要在下一个 chapter/section 前输出即可，要求 subsection 前输出是不必要的

**Comment by PositiveTom** [comment]
> 图片只需要在下一个 chapter/section 前输出即可，要求 subsection 前输出是不必要的

嗷嗷，我说错了，强制在section前输出怎么调整

**Comment by sikouhjw** [comment]
https://www.overleaf.com/learn/latex/Questions/How_can_I_get_my_table_or_figure_to_stay_where_they_are%2C_instead_of_going_to_the_next_page%3F

**Comment by PositiveTom** [comment]
用了hbt!参数好像还是不行，我其实只想这一个section自动布局到下一页图片到末尾就行，哪怕他空白出来，但是后台算法硬要塞一点到这里
<img width="530" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/6439a27e-8e39-473b-94a8-0de680595bfb">

**Comment by PositiveTom** [comment]
<img width="555" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/eebd08a1-ca46-4200-8846-5ee7a3fbb714">
我其实只想这一代文字塞到下一页图片的末尾即可，但是算法感觉调整不了，已经用了hbt!参数

**Comment by sikouhjw** [comment]
就这么没耐心看完全文吗？
> Alternatively, have a look at the [placeins package](http://texdoc.net/pkg/placeins), where you can add \FloatBarrier before the next \section—or automate this by using the section package option, i.e. write \usepackage[section]{placeins} in your preamble.

**Comment by PositiveTom** [comment]
> 就这么没耐心看完全文吗？
> 
> > Alternatively, have a look at the [placeins package](http://texdoc.net/pkg/placeins), where you can add \FloatBarrier before the next \section—or automate this by using the section package option, i.e. write \usepackage[section]{placeins} in your preamble.

好的好的，多谢哈，clearpage管用

**Comment by sikouhjw** [comment]
> 好的好的，多谢哈，clearpage管用

您好，您只需要用 `\usepackage[section]{placeins}` 即可。
