### ISSUE TITLE
想请问newtheorem的设置相关的问题：

### ISSUE THREAD

**Issue by PositiveTom** [mengchaoheng/SCUT_thesis#62]
我修改了scutthesis.cls中599～608行如下的内容：
\newtheoremstyle{definition}% name
  {0pt}%      Space above, empty = `usual value'
  {0pt}%      Space below
  {}% Body font \itshape
  {\parindent}%         Indent amount (empty = no indent, \parindent = para indent)
  {\bfseries}% Thm head font
  {}%        Punctuation after thm head（原来是:，我把这里去掉了，因为我导师说定理引理定义后面不出现冒号）
  {0.5em}% Space after thm head: \newline = linebreak
  {}%         Thm head spec
\theoremstyle{definition}
之后编译的结果图如下所示
<img width="307" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/0bbd0d2b-fb67-424b-aa67-1c6e5ce2ada1">
上图对应的latex代码如下所示：
\begin{definition}{\cite{zhao2022sufficient}}
.......
\end{definition}
可以发现引用参考文献前面有一个小空格，但是我希望参考文献紧贴着定义3.4，如下图所示：
<img width="237" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/07c9d265-c780-4db3-9918-f99807ee3e99">
我改怎么进行修改呢？
我尝试过以下的方法：
将scutthesis.cls中599～608行中的0.5em修改成0.0em，结果就变成下面这个样子了
<img width="242" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/39540325/32bc2b69-9c4d-4d7a-be8b-04756070a330">
第一个红框对应的latex代码如下：
\begin{definition}
.......
\end{definition}

**Comment by PositiveTom** [comment]
以及还有另外一个问题，我该如何调整   定义这两个词，与数字3.4之间的间距

**Comment by PositiveTom** [comment]
> 以及还有另外一个问题，我该如何调整 定义这两个词，与数字3.4之间的间距

这个问题我解决了，我改成如下的代码即可
\newtheorem{definition}{定义}[chapter]
之前定义后面有一个～

**Comment by mengchaoheng** [comment]
或者查一下历史issue，我记得几年前有人做过了？具体不记得了。

**Comment by PositiveTom** [comment]
> 或者查一下历史issue，我记得几年前有人做过了？具体不记得了。

似乎只看到了标题前后间距的设置，关于newtheorem的的关键字没有检索到

**Comment by mengchaoheng** [comment]
抱歉刚刚看错了，newtheorem部分和算法搞混了。如果有空的话，可以整理一下您的工作，把修改和效果都发一下，如果效果好的话，可以考虑推送pr给我合并。

**Comment by PositiveTom** [comment]
> 抱歉刚刚看错了，newtheorem部分和算法搞混了。如果有空的话，可以整理一下您的工作，把修改和效果都发一下，如果效果好的话，可以考虑推送pr给我合并。

好的，目前还有一个问题还没解决
