### ISSUE TITLE
目录的间距

### ISSUE THREAD

**Issue by PositiveTom** [mengchaoheng/SCUT_thesis#64]
想请问怎么调整目录间距

**Comment by mengchaoheng** [comment]
ChatGPT:

要调整 LaTeX 文档中目录的间距，您可以使用 titletoc 或 tocloft 等宏包来定制目录样式。下面是使用 titletoc 宏包来调整目录间距的示例：

首先，在导言区添加 titletoc 宏包，并使用 \titlecontents 命令来定制目录样式，包括间距设置：


\usepackage{titletoc}

% 调整章节之间的垂直间距
\titlecontents{chapter}[0em]
  {\addvspace{1em}} % 前间距
  {\bfseries\contentslabel{2em}} % 标签样式
  {\bfseries} % 章节标题样式
  {\titlerule*[0.5pc]{.}\contentspage} % 点线间距

在上面的代码中，\titlecontents{chapter}[0em] 设置了章节目录的格式，{\addvspace{1em}} 指定了章节之间的垂直间距为1em，您可以根据需要调整这个值。

您也可以类似地调整其他部分（如节、子节等）的目录间距，只需将 \titlecontents 中的参数替换为对应的部分即可。

需要注意的是，修改目录间距可能会影响文档的整体美观性，所以建议谨慎调整，并根据实际情况适当修改。
