### ISSUE TITLE
报错：LaTeX Error: Command \c@subfigure already defined.

### ISSUE THREAD

**Issue by Chupeng24** [mengchaoheng/SCUT_thesis#67]
导入subfigure包，发生报错，报错信息如下：

LaTeX Error: Command \c@subfigure already defined.

但是scutthesis文件的前面并没有定subfigure包呀？

**Comment by mengchaoheng** [comment]
cls文件检查一下？这部分当年因为一个博士的需求，增加一些贴图功能，深度研究过，现在已经忘了是怎么进行，其实有点重复造轮子，以前的旧模版也是。建议您看看使用说明[scutthesis.pdf](https://github.com/mengchaoheng/SCUT_thesis/blob/master/scutthesis.pdf)文件的案例是如何贴图的。如果还不能满足需求，再考虑自定义。
