### ISSUE TITLE
请问参考文献[A]是不是有点问题？

### ISSUE THREAD

**Issue by shawnl111** [mengchaoheng/SCUT_thesis#68]
<img width="709" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/38712239/04fa686d-e325-43fe-bee4-1c2bd35f3374">
<img width="552" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/38712239/a4c3b860-cdb8-4a6c-b5b9-ac65a0bdbcec">
从Google scholar直接导入的。但是看有点奇怪，国标里面好像也没有这个用法？

**Comment by mengchaoheng** [comment]
发现你导入的arxiv 的数据，建议去找正式发表的，没办法再看看怎么处理。计算机领域在arxiv而且还没被会议和期刊录用的论文比较多。相信这个领域的人编程能力。其他领域找到发表的地方下载元数据重新引用。

**Comment by shawnl111** [comment]
已经在arxiv官网重新导入了
<img width="527" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/38712239/f3f5a2f1-4c0d-4c3d-9804-d3dc7d6f215c">
现在看样子应该好点了？

**Comment by shawnl111** [comment]
参照这个 应该可以了
https://github.com/ustctug/ustcthesis/issues/365

**Comment by mengchaoheng** [comment]
这个可以，我也发现谷歌学术在引用元数据方面不太行，但是它数据库搜索可以。

**Comment by shawnl111** [comment]
好的谢谢～
我后面有添加了url
参考https://github.com/zepinglee/gbt7714-bibtex-style/issues/89
