### ISSUE TITLE
大写字母间距很大，（1）使用mathit之后，字体变细。（2）使用!减小字体间距不和谐。如何解决呢？

### ISSUE THREAD

**Issue by shawnl111** [mengchaoheng/SCUT_thesis#70]
大写字母间距很大，（1）使用mathit之后，字体变细。（2）使用!减小字体间距不和谐。如何解决呢？

<img width="307" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/38712239/0199de0b-4be8-40c9-9750-879635e247d8">

\begin{equation}
    \mathit{RMSE\%}RMSE=\sqrt{\frac{\sum_{i=1}^n[F(i)-\widehat{F}(i)]^2}{\sum_{i=1}^nF(i)^2}}\times100\%
    \label{eq:rmse}
\end{equation}  

<img width="298" alt="image" src="https://github.com/mengchaoheng/SCUT_thesis/assets/38712239/b6cf02de-caca-45e7-9afb-51fb54dbdbdb">

\begin{equation}
\mathit{Intensity}I\!ntensityIntensity=\sum_{t=1}^{n} H(t)
  \label{eq:2.18}
\end{equation}

**Comment by mengchaoheng** [comment]
公式的具体细节可以随便调，反正规范没有要求。现在的样子是好几届同学们提出的比较美观的。当然也可能有一些领域公式比较特殊，还望有更美观的样式可以分享

**Comment by mengchaoheng** [comment]
最近在研究[数学公式字体应该使用什么？](https://github.com/mengchaoheng/SCUT_thesis/issues/81#issuecomment-2552853803)，看到知乎问题[排版时何时应采用数学字体（math font），何时应采用文本字体（text font）](https://www.zhihu.com/question/461958690/answer/1912095673)。似乎有点启发，不过我暂时还没把[unicode-math 宏包文档](https://ctan.org/pkg/unicode-math)搞清楚。
