### ISSUE TITLE
公式字体问题

### ISSUE THREAD

**Issue by Thomastow** [mengchaoheng/SCUT_thesis#71]
公式字体不是times new roman，请问在哪儿修改。？

**Comment by mengchaoheng** [comment]
是times new roman，在cls文件前半部分，有一些类似宏定义然后再继续定义各个部分的字体，当然也可以在文中临时自定义。

**Comment by Thomas-Taotao** [comment]
> 是times new roman，在cls文件前半部分，有一些类似宏定义然后再继续定义各个部分的字体，当然也可以在文中临时自定义。

好的，谢谢，我意思是公式或者符号的字体，譬如，equation里面的内容或者$AAA$之类的，字体不是times new roman哈。正文文本的英文字体是times new roman

**Comment by mengchaoheng** [comment]
没研究过，应该是默认设置，目前可以用。

**Comment by Thomas-Taotao** [comment]
> 没研究过，应该是默认设置，目前可以用。

嗯嗯，好的，谢谢。

**Comment by PlexusChen** [comment]
同学您好，可以尝试在scutthesis.tex文件中添加以下代码尝试
```
\usepackage{mathptmx}
\setmainfont{Times New Roman}
```

**Comment by mengchaoheng** [comment]
> 同学您好，可以尝试在scutthesis.tex文件中添加以下代码尝试
> 
> ```
> \usepackage{mathptmx}
> \setmainfont{Times New Roman}
> ```

我修改为在.cls文件添加一行代码解决
```
\RequirePackage{mathptmx}
```
见fab535a23554cd57bb5aa554393ed7b910b4537f

**Comment by mengchaoheng** [comment]
最近的更新将取消这一修改字体策略。详见[数学公式字体应该使用什么？](https://github.com/mengchaoheng/SCUT_thesis/issues/81#issuecomment-2552853803)
