### ISSUE TITLE
目录字体为什么是蓝色的

### ISSUE THREAD

**Issue by Tiebao** [mengchaoheng/SCUT_thesis#72]
如题。目录字体是蓝色的，论文目录字体应该是黑色的吗

**Comment by mengchaoheng** [comment]
是的呀，注释有说明的。可以调，但是送审时其实也可以带颜色的，更美观

蒙超恒
----------------------------------
华南理工大学 自主系统与网络控制教育部重点实验室，广州510640
华南理工大学 广东省无人机系统工程技术研究中心，广州 510640 


Meng ChaoHeng
----------------------------------
Key Laboratory of Autonomous Systems and Networked Control，South China University of Technology， Guangzhou 510640，China


Unmaned Aerial Vehicle Systems Engineering Technology Research Center of Guangdong，South China University of Technology，Guangzhou 510640，China
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月22日 20:14 |
| 收件人 | mengchaoheng/SCUT_thesis ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [mengchaoheng/SCUT_thesis] 目录字体为什么是蓝色的 (Issue #72) |

如题。目录字体是蓝色的，论文目录字体应该是黑色的吗

**Comment by mengchaoheng** [comment]
@Tiebao 同学若使用win，可以帮忙测试刚刚推送的最新版吗？整理了文件目录，不知道路径在win下是否有效。

**Comment by mengchaoheng** [comment]
好的谢谢，不知道大家喜不喜欢这样整理后的版本。确实看起来简洁，但是也意味着.tex的内容复杂了（需要加上文件路径以及使能删除子文件夹中的辅助文件.aux）
