### ISSUE TITLE
关于公式字体Times New Roman的问题

### ISSUE THREAD

**Issue by PlexusChen** [mengchaoheng/SCUT_thesis#74]
之前看了其他人提的issue，发现latex提供的默认字体确实不是Times New Roman字体(下称Times)
在网上找了很久，发现用mathptmx宏包可以将公式调整为Times
但问题是这个包会更改公式外的正文字体，且这个字体却和Word中的Times差别很大
因此，需要在scutthesis.tex文件中，调用mathptmx宏包后，再用setmainfont设置Times字体，如下
```
\usepackage{mathptmx}
\setmainfont{Times New Roman}
```
latex的原字体
![1733204887630](https://github.com/user-attachments/assets/cca3a3ae-bf37-4a07-94b8-26e5c661b250)
更改后的字体
![1733204942275](https://github.com/user-attachments/assets/696766be-44a5-48e1-9a65-c58283c8dd2a)
Word中Mathtype的字体
![1733205081446](https://github.com/user-attachments/assets/4908c7d6-8d8d-464f-a4d1-19c975a97ca9)

**Comment by mengchaoheng** [comment]
我昨天检查issue 时也发现这个了，同学有空可以检查一下关闭的issue看看有没有啥问题可以帮忙解决的，或者提供一些思路，非常感谢。我也看看这个公式字体问题。


蒙超恒
----------------------------------
华南理工大学 自主系统与网络控制教育部重点实验室，广州510640
华南理工大学 广东省无人机系统工程技术研究中心，广州 510640 


Meng ChaoHeng
----------------------------------
Key Laboratory of Autonomous Systems and Networked Control，South China University of Technology， Guangzhou 510640，China


Unmaned Aerial Vehicle Systems Engineering Technology Research Center of Guangdong，South China University of Technology，Guangzhou 510640，China
---- 回复的原邮件 ----
| 发件人 | Chen ***@***.***> |
| 发送日期 | 2024年12月03日 13:59 |
| 收件人 | mengchaoheng/SCUT_thesis ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [mengchaoheng/SCUT_thesis] 关于公式字体Times New Roman的问题 (Issue #74) |

之前看了其他人提的issue，发现latex提供的默认字体确实不是Times New Roman字体(下称Times)
在网上找了很久，发现用mathptmx宏包可以将公式调整为Times
但问题是这个包会更改公式外的正文字体，且这个字体却和Word中的Times差别很大
因此，需要在scutthesis.tex文件中，调用mathptmx宏包后，再用setmainfont设置Times字体，如下

\usepackage{mathptmx}
\setmainfont{Times New Roman}


latex的原字体
1733204887630.png (view on web)
更改后的字体
1733204942275.png (view on web)
Word中Mathtype的字体
1733205081446.png (view on web)

**Comment by PlexusChen** [comment]
> 我昨天检查issue 时也发现这个了，同学有空可以检查一下关闭的issue看看有没有啥问题可以帮忙解决的，或者提供一些思路，非常感谢。我也看看这个公式字体问题。@PlexusChen

好的，遇到问题我会试试的，最近也要写论文了:D

**Comment by PlexusChen** [comment]
稍微调整了下，以便可以跨linux平台，在当前文件夹下创建一个dependencies文件夹，加入以下解压后的文件
[TIMES.tar.gz](https://github.com/user-attachments/files/17989028/TIMES.tar.gz)

在scutthesis.tex中添加以下代码
```
%% 设置Times New Roman字体
\usepackage{mathptmx}
\setmainfont[Path=./dependencies/, Mapping=tex-text, BoldFont=TIMESBD.TTF, ItalicFont=TIMESI.TTF]{TIMES.TTF}
```

**Comment by mengchaoheng** [comment]
邮件收到了您关于跨Linux平台的消息，这里却查不到。我之前也发现了在实验室的Linux 服务器上编译提示没有字体。若能把用到的字体都放在依赖里，这样不用每个人针对自己的平台安装就好了。我以前是把那个平台可能会缺的字体放win macOS Linux文件夹下，上个推送刚把它统一放一个文件夹里。

**Comment by PlexusChen** [comment]
> 邮件收到了您关于跨Linux平台的消息，这里却查不到。我之前也发现了在实验室的Linux 服务器上编译提示没有字体。若能把用到的字体都放在依赖里，这样不用每个人针对自己的平台安装就好了。我以前是把那个平台可能会缺的字体放win macOS Linux文件夹下，上个推送刚把它统一放一个文件夹里。

因为我删掉了，我后面发现我的wsl好像不需要额外配置字体，直接setmainfont就能完成编译。但可能不同的系统配置不太一样吧，我是直接从Windows的字体库里复制来的字体
[TIMES.tar.gz](https://github.com/user-attachments/files/18003376/TIMES.tar.gz)
如果发现自己的系统上没有字体的话，可以改为以下命令
```
\usepackage{mathptmx}
\setmainfont[Path=./dependencies/, Mapping=tex-text, BoldFont=TIMESBD.TTF, ItalicFont=TIMESI.TTF]{TIMES.TTF}
```

**Comment by mengchaoheng** [comment]
是的，每个平台不太一样，有时候安装系统不一定有所需字体，目前把常用的字体放文件夹里也是一种办法吧。若在模版里用命令加载，若每次都加载不知道会不会增加编译时间。

**Comment by mengchaoheng** [comment]
问题通过添加一行公式解决：
```
\RequirePackage{mathptmx}
```
见fab535a23554cd57bb5aa554393ed7b910b4537f

**Comment by mengchaoheng** [comment]
提问chatGPT：latex公式里使用times new roman字体，使用命令：
```
 \RequirePackage{mathptmx}  
\setmainfont[Mapping=tex-text]{Times New Roman}
```
这里有什么问题吗？

chatGPT回答：

从您提供的命令和示例来看，以下是可能需要注意的问题：

---

### 1. **`\RequirePackage{mathptmx}` 的局限性**
- **问题**：`mathptmx` 包虽然将数学公式字体设置为 Times 风格，但它不支持 Unicode 字符和较新的数学符号（例如部分特殊字符可能无法正确渲染）。
- **解决方案**：
  如果需要更现代的数学字体支持，建议使用 `newtxmath` 替代：
  ```latex
  \usepackage{newtxtext,newtxmath}
  ```
  这样能提供更全面的数学符号支持，同时仍然使用 Times 风格字体。

---

### 2. **`\setmainfont` 的依赖问题**
- **问题**：`\setmainfont` 命令要求使用 XeLaTeX 或 LuaLaTeX 编译。如果您使用的是 pdfLaTeX，无法直接加载系统字体。
- **解决方案**：确保使用 XeLaTeX 或 LuaLaTeX 编译。通过以下方式验证编译方式：
  - 使用命令行：`xelatex yourfile.tex`
  - 在编辑器（如 Overleaf 或 Texmaker）中选择 XeLaTeX。

---

### 3. **系统字体名称**
- **问题**：`\setmainfont{Times New Roman}` 的字体名称需要与系统实际字体名称匹配。例如：
  - 在 macOS 上，字体名称可能为 `Times`.
  - 在 Windows 上，字体名称通常为 `Times New Roman`。
  - 在 Linux 上，可能需要安装 `Microsoft Fonts` 包来提供 Times New Roman 字体。
- **解决方案**：
  确认系统中 Times New Roman 字体的正确名称。如果不确定字体名称，可以使用以下命令检查：
  ```bash
  fc-list | grep "Times"
  ```

---

### 4. **数学公式与正文字体一致性**
- **问题**：`mathptmx` 会将数学公式改为 Times 风格，但正文字体由 `\setmainfont` 设置。如果两者配置不一致，可能会导致视觉效果不统一。
- **解决方案**：直接使用 `newtxtext` 和 `newtxmath` 作为替代，统一设置正文和数学公式字体。

示例：
```latex
\documentclass{article}
\usepackage{newtxtext,newtxmath} % Times 风格文本与数学
\usepackage{fontspec}
\setmainfont{Times New Roman} % 正文字体

\begin{document}
正文内容：这是 Times New Roman。

数学公式：$a^2 + b^2 = c^2$
\end{document}
```

---

### 5. **兼容性问题**
- **问题**：部分复杂公式可能需要更多数学符号支持，而 `mathptmx` 或 `newtxmath` 默认不包含。
- **解决方案**：结合 `amsmath` 等增强数学包，确保公式正常渲染。例如：
  ```latex
  \usepackage{amsmath}
  ```

---

### 检查清单
如果遇到问题，您可以按以下步骤检查：
1. 确认使用的是 XeLaTeX 或 LuaLaTeX 编译。
2. 确认系统中已安装 Times New Roman 字体，且名称正确。
3. 确保数学公式与正文的字体一致性（推荐使用 `newtxtext` 和 `newtxmath`）。
4. 如果有特殊数学符号需求，加载 `amsmath` 和其他符号包。

---

如果这些问题都解决了，那么您的代码应该可以正常工作。如果仍有其他疑问，请告诉我具体症状或报错信息！

**Comment by mengchaoheng** [comment]
最近的更新将取消这一修改字体策略。详见[数学公式字体应该使用什么？](https://github.com/mengchaoheng/SCUT_thesis/issues/81#issuecomment-2552853803)
