### ISSUE TITLE
关于长章名换行后不居中的问题

### ISSUE THREAD

**Issue by PlexusChen** [mengchaoheng/SCUT_thesis#79]
在输入较长章名时，会发现换行后的位置不居中
```
\chapter{粘滞阻尼器—支撑—半刚性钢框架结构动力时程分析}
```
![1733548329660](https://github.com/user-attachments/assets/40242a0d-44d3-4204-ae8e-f98d2628914e)
而如果添加换行符，又会出现页眉一起换行的情况
```
\chapter{粘滞阻尼器—支撑—半刚性钢框架结构动力时程分析}
```
![1733548430504](https://github.com/user-attachments/assets/0c4a44be-762d-46a0-8b95-0b1cc7f12ff9)

可以通过在页眉获取章名的命令\chaptermark中去掉换行符进行优化
```
% 原命令
\renewcommand{\chaptermark}[1]{\markboth{\chaptername\ #1}{}}

% 修改后命令
\renewcommand{\chaptermark}[1]{%
  \StrSubstitute{#1}{\\}{ }[\cleanTitle]%
  \markboth{\chaptername\ \cleanTitle}{}
}
```

**Comment by mengchaoheng** [comment]
同学您好，前面issues 有记录，印象中好像有个同学也曾经遇到过这个问题。他好像解决了。还有一种思路，名字重新好好斟酌一下😂

**Comment by PlexusChen** [comment]
我看了下之前的issue，好像是需要自己手动输入标题，设置页眉，利用\markboth{}命令
而这样修改的话只需要在章名内加换行符就好了，页眉会自动把章名中的换行符替换掉

**Comment by PlexusChen** [comment]
另外一个是通过以下命令
```
\chapter[粘滞阻尼器—支撑—半刚性钢框架结构动力时程分析]{粘滞阻尼器—支撑—半刚性钢框架结构\\动力时程分析}
```
其实也可以
